// Code generated by cmd/updatesdkartifacts; DO NOT EDIT.

package protocol

import "encoding/json"

type AbsolutePathBuf string

type AccountLoginCompletedNotification struct {
	Error   *string `json:"error,omitempty"`
	LoginId *string `json:"loginId,omitempty"`
	Success bool    `json:"success"`
}

type AccountRateLimitsUpdatedNotification struct {
	RateLimits RateLimitSnapshot `json:"rateLimits"`
}

type AccountUpdatedNotification struct {
	AuthMode *AuthMode `json:"authMode,omitempty"`
	PlanType *PlanType `json:"planType,omitempty"`
}

type AdditionalFileSystemPermissions struct {
	Read  []V2AbsolutePathBuf `json:"read,omitempty"`
	Write []V2AbsolutePathBuf `json:"write,omitempty"`
}

type AdditionalNetworkPermissions struct {
	Enabled *bool `json:"enabled,omitempty"`
}

type AgentMessageDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemId   string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type AppBranding struct {
	Category          *string `json:"category,omitempty"`
	Developer         *string `json:"developer,omitempty"`
	IsDiscoverableApp bool    `json:"isDiscoverableApp"`
	PrivacyPolicy     *string `json:"privacyPolicy,omitempty"`
	TermsOfService    *string `json:"termsOfService,omitempty"`
	Website           *string `json:"website,omitempty"`
}

type AppInfo struct {
	AppMetadata         *AppMetadata      `json:"appMetadata,omitempty"`
	Branding            *AppBranding      `json:"branding,omitempty"`
	Description         *string           `json:"description,omitempty"`
	DistributionChannel *string           `json:"distributionChannel,omitempty"`
	ID                  string            `json:"id"`
	InstallUrl          *string           `json:"installUrl,omitempty"`
	IsAccessible        *bool             `json:"isAccessible,omitempty"`
	IsEnabled           *bool             `json:"isEnabled,omitempty"`
	Labels              map[string]string `json:"labels,omitempty"`
	LogoUrl             *string           `json:"logoUrl,omitempty"`
	LogoUrlDark         *string           `json:"logoUrlDark,omitempty"`
	Name                string            `json:"name"`
	PluginDisplayNames  []string          `json:"pluginDisplayNames,omitempty"`
}

type AppListUpdatedNotification struct {
	Data []AppInfo `json:"data"`
}

type AppMetadata struct {
	Categories                 []string        `json:"categories,omitempty"`
	Developer                  *string         `json:"developer,omitempty"`
	FirstPartyRequiresInstall  *bool           `json:"firstPartyRequiresInstall,omitempty"`
	FirstPartyType             *string         `json:"firstPartyType,omitempty"`
	Review                     *AppReview      `json:"review,omitempty"`
	Screenshots                []AppScreenshot `json:"screenshots,omitempty"`
	SeoDescription             *string         `json:"seoDescription,omitempty"`
	ShowInComposerWhenUnlinked *bool           `json:"showInComposerWhenUnlinked,omitempty"`
	SubCategories              []string        `json:"subCategories,omitempty"`
	Version                    *string         `json:"version,omitempty"`
	VersionId                  *string         `json:"versionId,omitempty"`
	VersionNotes               *string         `json:"versionNotes,omitempty"`
}

type AppReview struct {
	Status string `json:"status"`
}

type AppScreenshot struct {
	FileId     *string `json:"fileId,omitempty"`
	URL        *string `json:"url,omitempty"`
	UserPrompt string  `json:"userPrompt"`
}

type ApplyPatchApprovalParams struct {
	CallId         string                `json:"callId"`
	ConversationId V2ThreadId            `json:"conversationId"`
	FileChanges    map[string]FileChange `json:"fileChanges"`
	GrantRoot      *string               `json:"grantRoot,omitempty"`
	Reason         *string               `json:"reason,omitempty"`
}

type ApprovalsReviewer string

const (
	ApprovalsReviewerUser             ApprovalsReviewer = "user"
	ApprovalsReviewerGuardianSubagent ApprovalsReviewer = "guardian_subagent"
)

type AskForApproval = json.RawMessage

type AuthMode string

const (
	AuthModeApikey            AuthMode = "apikey"
	AuthModeChatgpt           AuthMode = "chatgpt"
	AuthModeChatgptAuthTokens AuthMode = "chatgptAuthTokens"
)

type ByteRange struct {
	End   uint64 `json:"end"`
	Start uint64 `json:"start"`
}

type ChatgptAuthTokensRefreshParams struct {
	PreviousAccountId *string                        `json:"previousAccountId,omitempty"`
	Reason            ChatgptAuthTokensRefreshReason `json:"reason"`
}

type ChatgptAuthTokensRefreshReason string

const ChatgptAuthTokensRefreshReasonUnauthorized ChatgptAuthTokensRefreshReason = "unauthorized"

type ClientInfo struct {
	Name    string  `json:"name"`
	Title   *string `json:"title,omitempty"`
	Version string  `json:"version"`
}

type CodexErrorInfo = json.RawMessage

type CollabAgentState struct {
	Message *string           `json:"message,omitempty"`
	Status  CollabAgentStatus `json:"status"`
}

type CollabAgentStatus string

const (
	CollabAgentStatusPendingInit CollabAgentStatus = "pendingInit"
	CollabAgentStatusRunning     CollabAgentStatus = "running"
	CollabAgentStatusInterrupted CollabAgentStatus = "interrupted"
	CollabAgentStatusCompleted   CollabAgentStatus = "completed"
	CollabAgentStatusErrored     CollabAgentStatus = "errored"
	CollabAgentStatusShutdown    CollabAgentStatus = "shutdown"
	CollabAgentStatusNotFound    CollabAgentStatus = "notFound"
)

type CollabAgentTool string

const (
	CollabAgentToolSpawnAgent  CollabAgentTool = "spawnAgent"
	CollabAgentToolSendInput   CollabAgentTool = "sendInput"
	CollabAgentToolResumeAgent CollabAgentTool = "resumeAgent"
	CollabAgentToolWait        CollabAgentTool = "wait"
	CollabAgentToolCloseAgent  CollabAgentTool = "closeAgent"
)

type CollabAgentToolCallStatus string

const (
	CollabAgentToolCallStatusInProgress CollabAgentToolCallStatus = "inProgress"
	CollabAgentToolCallStatusCompleted  CollabAgentToolCallStatus = "completed"
	CollabAgentToolCallStatusFailed     CollabAgentToolCallStatus = "failed"
)

type CommandAction = json.RawMessage

type CommandExecOutputDeltaNotification struct {
	CapReached  bool                    `json:"capReached"`
	DeltaBase64 string                  `json:"deltaBase64"`
	ProcessId   string                  `json:"processId"`
	Stream      CommandExecOutputStream `json:"stream"`
}

type CommandExecOutputStream string

const (
	CommandExecOutputStreamStdout CommandExecOutputStream = "stdout"
	CommandExecOutputStreamStderr CommandExecOutputStream = "stderr"
)

type CommandExecutionOutputDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemId   string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type CommandExecutionRequestApprovalParams struct {
	ApprovalId                      *string                  `json:"approvalId,omitempty"`
	Command                         *string                  `json:"command,omitempty"`
	CommandActions                  []V2CommandAction        `json:"commandActions,omitempty"`
	CWD                             *string                  `json:"cwd,omitempty"`
	ItemId                          string                   `json:"itemId"`
	NetworkApprovalContext          *NetworkApprovalContext  `json:"networkApprovalContext,omitempty"`
	ProposedExecpolicyAmendment     []string                 `json:"proposedExecpolicyAmendment,omitempty"`
	ProposedNetworkPolicyAmendments []NetworkPolicyAmendment `json:"proposedNetworkPolicyAmendments,omitempty"`
	Reason                          *string                  `json:"reason,omitempty"`
	ThreadId                        string                   `json:"threadId"`
	TurnId                          string                   `json:"turnId"`
}

type CommandExecutionStatus string

const (
	CommandExecutionStatusInProgress CommandExecutionStatus = "inProgress"
	CommandExecutionStatusCompleted  CommandExecutionStatus = "completed"
	CommandExecutionStatusFailed     CommandExecutionStatus = "failed"
	CommandExecutionStatusDeclined   CommandExecutionStatus = "declined"
)

type ConfigWarningNotification struct {
	Details *string    `json:"details,omitempty"`
	Path    *string    `json:"path,omitempty"`
	Range   *TextRange `json:"range,omitempty"`
	Summary string     `json:"summary"`
}

type ContextCompactedNotification struct {
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type CreditsSnapshot struct {
	Balance    *string `json:"balance,omitempty"`
	HasCredits bool    `json:"hasCredits"`
	Unlimited  bool    `json:"unlimited"`
}

type DeprecationNoticeNotification struct {
	Details *string `json:"details,omitempty"`
	Summary string  `json:"summary"`
}

type DynamicToolCallOutputContentItem = json.RawMessage

type DynamicToolCallParams struct {
	Arguments any    `json:"arguments"`
	CallId    string `json:"callId"`
	ThreadId  string `json:"threadId"`
	Tool      string `json:"tool"`
	TurnId    string `json:"turnId"`
}

type DynamicToolCallStatus string

const (
	DynamicToolCallStatusInProgress DynamicToolCallStatus = "inProgress"
	DynamicToolCallStatusCompleted  DynamicToolCallStatus = "completed"
	DynamicToolCallStatusFailed     DynamicToolCallStatus = "failed"
)

type ErrorNotification struct {
	Error     TurnError `json:"error"`
	ThreadId  string    `json:"threadId"`
	TurnId    string    `json:"turnId"`
	WillRetry bool      `json:"willRetry"`
}

type ExecCommandApprovalParams struct {
	ApprovalId     *string         `json:"approvalId,omitempty"`
	CallId         string          `json:"callId"`
	Command        []string        `json:"command"`
	ConversationId V2ThreadId      `json:"conversationId"`
	CWD            string          `json:"cwd"`
	ParsedCmd      []ParsedCommand `json:"parsedCmd"`
	Reason         *string         `json:"reason,omitempty"`
}

type FileChange = json.RawMessage

type FileChangeOutputDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemId   string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type FileChangeRequestApprovalParams struct {
	GrantRoot *string `json:"grantRoot,omitempty"`
	ItemId    string  `json:"itemId"`
	Reason    *string `json:"reason,omitempty"`
	ThreadId  string  `json:"threadId"`
	TurnId    string  `json:"turnId"`
}

type FileUpdateChange struct {
	Diff string          `json:"diff"`
	Kind PatchChangeKind `json:"kind"`
	Path string          `json:"path"`
}

type FuzzyFileSearchResult struct {
	FileName string   `json:"file_name"`
	Indices  []uint32 `json:"indices,omitempty"`
	Path     string   `json:"path"`
	Root     string   `json:"root"`
	Score    uint32   `json:"score"`
}

type FuzzyFileSearchSessionCompletedNotification struct {
	SessionId string `json:"sessionId"`
}

type FuzzyFileSearchSessionUpdatedNotification struct {
	Files     []FuzzyFileSearchResult `json:"files"`
	Query     string                  `json:"query"`
	SessionId string                  `json:"sessionId"`
}

type GitInfo struct {
	Branch    *string `json:"branch,omitempty"`
	OriginUrl *string `json:"originUrl,omitempty"`
	Sha       *string `json:"sha,omitempty"`
}

type GuardianApprovalReview struct {
	Rationale *string                      `json:"rationale,omitempty"`
	RiskLevel *GuardianRiskLevel           `json:"riskLevel,omitempty"`
	RiskScore *uint64                      `json:"riskScore,omitempty"`
	Status    GuardianApprovalReviewStatus `json:"status"`
}

type GuardianApprovalReviewStatus string

const (
	GuardianApprovalReviewStatusInProgress GuardianApprovalReviewStatus = "inProgress"
	GuardianApprovalReviewStatusApproved   GuardianApprovalReviewStatus = "approved"
	GuardianApprovalReviewStatusDenied     GuardianApprovalReviewStatus = "denied"
	GuardianApprovalReviewStatusAborted    GuardianApprovalReviewStatus = "aborted"
)

type GuardianRiskLevel string

const (
	GuardianRiskLevelLow    GuardianRiskLevel = "low"
	GuardianRiskLevelMedium GuardianRiskLevel = "medium"
	GuardianRiskLevelHigh   GuardianRiskLevel = "high"
)

type HookCompletedNotification struct {
	Run      HookRunSummary `json:"run"`
	ThreadId string         `json:"threadId"`
	TurnId   *string        `json:"turnId,omitempty"`
}

type HookEventName string

const (
	HookEventNameSessionStart HookEventName = "sessionStart"
	HookEventNameStop         HookEventName = "stop"
)

type HookExecutionMode string

const (
	HookExecutionModeSync  HookExecutionMode = "sync"
	HookExecutionModeAsync HookExecutionMode = "async"
)

type HookHandlerType string

const (
	HookHandlerTypeCommand HookHandlerType = "command"
	HookHandlerTypePrompt  HookHandlerType = "prompt"
	HookHandlerTypeAgent   HookHandlerType = "agent"
)

type HookOutputEntry struct {
	Kind HookOutputEntryKind `json:"kind"`
	Text string              `json:"text"`
}

type HookOutputEntryKind string

const (
	HookOutputEntryKindWarning  HookOutputEntryKind = "warning"
	HookOutputEntryKindStop     HookOutputEntryKind = "stop"
	HookOutputEntryKindFeedback HookOutputEntryKind = "feedback"
	HookOutputEntryKindContext  HookOutputEntryKind = "context"
	HookOutputEntryKindError    HookOutputEntryKind = "error"
)

type HookRunStatus string

const (
	HookRunStatusRunning   HookRunStatus = "running"
	HookRunStatusCompleted HookRunStatus = "completed"
	HookRunStatusFailed    HookRunStatus = "failed"
	HookRunStatusBlocked   HookRunStatus = "blocked"
	HookRunStatusStopped   HookRunStatus = "stopped"
)

type HookRunSummary struct {
	CompletedAt   *int64            `json:"completedAt,omitempty"`
	DisplayOrder  int64             `json:"displayOrder"`
	DurationMs    *int64            `json:"durationMs,omitempty"`
	Entries       []HookOutputEntry `json:"entries"`
	EventName     HookEventName     `json:"eventName"`
	ExecutionMode HookExecutionMode `json:"executionMode"`
	HandlerType   HookHandlerType   `json:"handlerType"`
	ID            string            `json:"id"`
	Scope         HookScope         `json:"scope"`
	SourcePath    string            `json:"sourcePath"`
	StartedAt     int64             `json:"startedAt"`
	Status        HookRunStatus     `json:"status"`
	StatusMessage *string           `json:"statusMessage,omitempty"`
}

type HookScope string

const (
	HookScopeThread HookScope = "thread"
	HookScopeTurn   HookScope = "turn"
)

type HookStartedNotification struct {
	Run      HookRunSummary `json:"run"`
	ThreadId string         `json:"threadId"`
	TurnId   *string        `json:"turnId,omitempty"`
}

type InitializeCapabilities struct {
	ExperimentalApi           *bool    `json:"experimentalApi,omitempty"`
	OptOutNotificationMethods []string `json:"optOutNotificationMethods,omitempty"`
}

type InitializeParams struct {
	Capabilities *InitializeCapabilities `json:"capabilities,omitempty"`
	ClientInfo   ClientInfo              `json:"clientInfo"`
}

type InitializeResponse struct {
	PlatformFamily string `json:"platformFamily"`
	PlatformOs     string `json:"platformOs"`
	UserAgent      string `json:"userAgent"`
}

type InputModality string

const (
	InputModalityText  InputModality = "text"
	InputModalityImage InputModality = "image"
)

type ItemCompletedNotification struct {
	Item     ThreadItem `json:"item"`
	ThreadId string     `json:"threadId"`
	TurnId   string     `json:"turnId"`
}

type ItemGuardianApprovalReviewCompletedNotification struct {
	Action       any                    `json:"action,omitempty"`
	Review       GuardianApprovalReview `json:"review"`
	TargetItemId string                 `json:"targetItemId"`
	ThreadId     string                 `json:"threadId"`
	TurnId       string                 `json:"turnId"`
}

type ItemGuardianApprovalReviewStartedNotification struct {
	Action       any                    `json:"action,omitempty"`
	Review       GuardianApprovalReview `json:"review"`
	TargetItemId string                 `json:"targetItemId"`
	ThreadId     string                 `json:"threadId"`
	TurnId       string                 `json:"turnId"`
}

type ItemStartedNotification struct {
	Item     ThreadItem `json:"item"`
	ThreadId string     `json:"threadId"`
	TurnId   string     `json:"turnId"`
}

type McpElicitationArrayType string

const McpElicitationArrayTypeArray McpElicitationArrayType = "array"

type McpElicitationBooleanSchema struct {
	Default     *bool                     `json:"default,omitempty"`
	Description *string                   `json:"description,omitempty"`
	Title       *string                   `json:"title,omitempty"`
	Type        McpElicitationBooleanType `json:"type"`
}

type McpElicitationBooleanType string

const McpElicitationBooleanTypeBoolean McpElicitationBooleanType = "boolean"

type McpElicitationConstOption struct {
	Const string `json:"const"`
	Title string `json:"title"`
}

type McpElicitationEnumSchema = json.RawMessage

type McpElicitationLegacyTitledEnumSchema struct {
	Default     *string                  `json:"default,omitempty"`
	Description *string                  `json:"description,omitempty"`
	Enum        []string                 `json:"enum"`
	EnumNames   []string                 `json:"enumNames,omitempty"`
	Title       *string                  `json:"title,omitempty"`
	Type        McpElicitationStringType `json:"type"`
}

type McpElicitationMultiSelectEnumSchema = json.RawMessage

type McpElicitationNumberSchema struct {
	Default     *float64                 `json:"default,omitempty"`
	Description *string                  `json:"description,omitempty"`
	Maximum     *float64                 `json:"maximum,omitempty"`
	Minimum     *float64                 `json:"minimum,omitempty"`
	Title       *string                  `json:"title,omitempty"`
	Type        McpElicitationNumberType `json:"type"`
}

type McpElicitationNumberType string

const (
	McpElicitationNumberTypeNumber  McpElicitationNumberType = "number"
	McpElicitationNumberTypeInteger McpElicitationNumberType = "integer"
)

type McpElicitationObjectType string

const McpElicitationObjectTypeObject McpElicitationObjectType = "object"

type McpElicitationPrimitiveSchema = json.RawMessage

type McpElicitationSchema struct {
	Schema     *string                                  `json:"$schema,omitempty"`
	Properties map[string]McpElicitationPrimitiveSchema `json:"properties"`
	Required   []string                                 `json:"required,omitempty"`
	Type       McpElicitationObjectType                 `json:"type"`
}

type McpElicitationSingleSelectEnumSchema = json.RawMessage

type McpElicitationStringFormat string

const (
	McpElicitationStringFormatEmail    McpElicitationStringFormat = "email"
	McpElicitationStringFormatURI      McpElicitationStringFormat = "uri"
	McpElicitationStringFormatDate     McpElicitationStringFormat = "date"
	McpElicitationStringFormatDateTime McpElicitationStringFormat = "date-time"
)

type McpElicitationStringSchema struct {
	Default     *string                     `json:"default,omitempty"`
	Description *string                     `json:"description,omitempty"`
	Format      *McpElicitationStringFormat `json:"format,omitempty"`
	MaxLength   *uint32                     `json:"maxLength,omitempty"`
	MinLength   *uint32                     `json:"minLength,omitempty"`
	Title       *string                     `json:"title,omitempty"`
	Type        McpElicitationStringType    `json:"type"`
}

type McpElicitationStringType string

const McpElicitationStringTypeString McpElicitationStringType = "string"

type McpElicitationTitledEnumItems struct {
	AnyOf []McpElicitationConstOption `json:"anyOf"`
}

type McpElicitationTitledMultiSelectEnumSchema struct {
	Default     []string                      `json:"default,omitempty"`
	Description *string                       `json:"description,omitempty"`
	Items       McpElicitationTitledEnumItems `json:"items"`
	MaxItems    *uint64                       `json:"maxItems,omitempty"`
	MinItems    *uint64                       `json:"minItems,omitempty"`
	Title       *string                       `json:"title,omitempty"`
	Type        McpElicitationArrayType       `json:"type"`
}

type McpElicitationTitledSingleSelectEnumSchema struct {
	Default     *string                     `json:"default,omitempty"`
	Description *string                     `json:"description,omitempty"`
	OneOf       []McpElicitationConstOption `json:"oneOf"`
	Title       *string                     `json:"title,omitempty"`
	Type        McpElicitationStringType    `json:"type"`
}

type McpElicitationUntitledEnumItems struct {
	Enum []string                 `json:"enum"`
	Type McpElicitationStringType `json:"type"`
}

type McpElicitationUntitledMultiSelectEnumSchema struct {
	Default     []string                        `json:"default,omitempty"`
	Description *string                         `json:"description,omitempty"`
	Items       McpElicitationUntitledEnumItems `json:"items"`
	MaxItems    *uint64                         `json:"maxItems,omitempty"`
	MinItems    *uint64                         `json:"minItems,omitempty"`
	Title       *string                         `json:"title,omitempty"`
	Type        McpElicitationArrayType         `json:"type"`
}

type McpElicitationUntitledSingleSelectEnumSchema struct {
	Default     *string                  `json:"default,omitempty"`
	Description *string                  `json:"description,omitempty"`
	Enum        []string                 `json:"enum"`
	Title       *string                  `json:"title,omitempty"`
	Type        McpElicitationStringType `json:"type"`
}

type McpServerElicitationRequestParams struct {
	ServerName string  `json:"serverName"`
	ThreadId   string  `json:"threadId"`
	TurnId     *string `json:"turnId,omitempty"`
}

type McpServerOauthLoginCompletedNotification struct {
	Error   *string `json:"error,omitempty"`
	Name    string  `json:"name"`
	Success bool    `json:"success"`
}

type McpToolCallError struct {
	Message string `json:"message"`
}

type McpToolCallProgressNotification struct {
	ItemId   string `json:"itemId"`
	Message  string `json:"message"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type McpToolCallResult struct {
	Content           []any `json:"content"`
	StructuredContent any   `json:"structuredContent,omitempty"`
}

type McpToolCallStatus string

const (
	McpToolCallStatusInProgress McpToolCallStatus = "inProgress"
	McpToolCallStatusCompleted  McpToolCallStatus = "completed"
	McpToolCallStatusFailed     McpToolCallStatus = "failed"
)

type MessagePhase string

const (
	MessagePhaseCommentary  MessagePhase = "commentary"
	MessagePhaseFinalAnswer MessagePhase = "final_answer"
)

type Model struct {
	AvailabilityNux           *ModelAvailabilityNux   `json:"availabilityNux,omitempty"`
	DefaultReasoningEffort    ReasoningEffort         `json:"defaultReasoningEffort"`
	Description               string                  `json:"description"`
	DisplayName               string                  `json:"displayName"`
	Hidden                    bool                    `json:"hidden"`
	ID                        string                  `json:"id"`
	InputModalities           []InputModality         `json:"inputModalities,omitempty"`
	IsDefault                 bool                    `json:"isDefault"`
	Model                     string                  `json:"model"`
	SupportedReasoningEfforts []ReasoningEffortOption `json:"supportedReasoningEfforts"`
	SupportsPersonality       *bool                   `json:"supportsPersonality,omitempty"`
	Upgrade                   *string                 `json:"upgrade,omitempty"`
	UpgradeInfo               *ModelUpgradeInfo       `json:"upgradeInfo,omitempty"`
}

type ModelAvailabilityNux struct {
	Message string `json:"message"`
}

type ModelListParams struct {
	Cursor        *string `json:"cursor,omitempty"`
	IncludeHidden *bool   `json:"includeHidden,omitempty"`
	Limit         *uint32 `json:"limit,omitempty"`
}

type ModelListResponse struct {
	Data       []Model `json:"data"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

type ModelRerouteReason string

const ModelRerouteReasonHighRiskCyberActivity ModelRerouteReason = "highRiskCyberActivity"

type ModelReroutedNotification struct {
	FromModel string             `json:"fromModel"`
	Reason    ModelRerouteReason `json:"reason"`
	ThreadId  string             `json:"threadId"`
	ToModel   string             `json:"toModel"`
	TurnId    string             `json:"turnId"`
}

type ModelUpgradeInfo struct {
	MigrationMarkdown *string `json:"migrationMarkdown,omitempty"`
	Model             string  `json:"model"`
	ModelLink         *string `json:"modelLink,omitempty"`
	UpgradeCopy       *string `json:"upgradeCopy,omitempty"`
}

type NetworkAccess string

const (
	NetworkAccessRestricted NetworkAccess = "restricted"
	NetworkAccessEnabled    NetworkAccess = "enabled"
)

type NetworkApprovalContext struct {
	Host     string                  `json:"host"`
	Protocol NetworkApprovalProtocol `json:"protocol"`
}

type NetworkApprovalProtocol string

const (
	NetworkApprovalProtocolHttp      NetworkApprovalProtocol = "http"
	NetworkApprovalProtocolHttps     NetworkApprovalProtocol = "https"
	NetworkApprovalProtocolSocks5Tcp NetworkApprovalProtocol = "socks5Tcp"
	NetworkApprovalProtocolSocks5Udp NetworkApprovalProtocol = "socks5Udp"
)

type NetworkPolicyAmendment struct {
	Action NetworkPolicyRuleAction `json:"action"`
	Host   string                  `json:"host"`
}

type NetworkPolicyRuleAction string

const (
	NetworkPolicyRuleActionAllow NetworkPolicyRuleAction = "allow"
	NetworkPolicyRuleActionDeny  NetworkPolicyRuleAction = "deny"
)

type ParsedCommand = json.RawMessage

type PatchApplyStatus string

const (
	PatchApplyStatusInProgress PatchApplyStatus = "inProgress"
	PatchApplyStatusCompleted  PatchApplyStatus = "completed"
	PatchApplyStatusFailed     PatchApplyStatus = "failed"
	PatchApplyStatusDeclined   PatchApplyStatus = "declined"
)

type PatchChangeKind = json.RawMessage

type PermissionsRequestApprovalParams struct {
	ItemId      string                   `json:"itemId"`
	Permissions RequestPermissionProfile `json:"permissions"`
	Reason      *string                  `json:"reason,omitempty"`
	ThreadId    string                   `json:"threadId"`
	TurnId      string                   `json:"turnId"`
}

type Personality string

const (
	PersonalityNone      Personality = "none"
	PersonalityFriendly  Personality = "friendly"
	PersonalityPragmatic Personality = "pragmatic"
)

type PlanDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemId   string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type PlanType string

const (
	PlanTypeFree       PlanType = "free"
	PlanTypeGo         PlanType = "go"
	PlanTypePlus       PlanType = "plus"
	PlanTypePro        PlanType = "pro"
	PlanTypeTeam       PlanType = "team"
	PlanTypeBusiness   PlanType = "business"
	PlanTypeEnterprise PlanType = "enterprise"
	PlanTypeEdu        PlanType = "edu"
	PlanTypeUnknown    PlanType = "unknown"
)

type RateLimitSnapshot struct {
	Credits   *CreditsSnapshot `json:"credits,omitempty"`
	LimitId   *string          `json:"limitId,omitempty"`
	LimitName *string          `json:"limitName,omitempty"`
	PlanType  *PlanType        `json:"planType,omitempty"`
	Primary   *RateLimitWindow `json:"primary,omitempty"`
	Secondary *RateLimitWindow `json:"secondary,omitempty"`
}

type RateLimitWindow struct {
	ResetsAt           *int64 `json:"resetsAt,omitempty"`
	UsedPercent        int32  `json:"usedPercent"`
	WindowDurationMins *int64 `json:"windowDurationMins,omitempty"`
}

type ReadOnlyAccess = json.RawMessage

type ReasoningEffort string

const (
	ReasoningEffortNone    ReasoningEffort = "none"
	ReasoningEffortMinimal ReasoningEffort = "minimal"
	ReasoningEffortLow     ReasoningEffort = "low"
	ReasoningEffortMedium  ReasoningEffort = "medium"
	ReasoningEffortHigh    ReasoningEffort = "high"
	ReasoningEffortXhigh   ReasoningEffort = "xhigh"
)

type ReasoningEffortOption struct {
	Description     string          `json:"description"`
	ReasoningEffort ReasoningEffort `json:"reasoningEffort"`
}

type ReasoningSummary = json.RawMessage

type ReasoningSummaryPartAddedNotification struct {
	ItemId       string `json:"itemId"`
	SummaryIndex int64  `json:"summaryIndex"`
	ThreadId     string `json:"threadId"`
	TurnId       string `json:"turnId"`
}

type ReasoningSummaryTextDeltaNotification struct {
	Delta        string `json:"delta"`
	ItemId       string `json:"itemId"`
	SummaryIndex int64  `json:"summaryIndex"`
	ThreadId     string `json:"threadId"`
	TurnId       string `json:"turnId"`
}

type ReasoningTextDeltaNotification struct {
	ContentIndex int64  `json:"contentIndex"`
	Delta        string `json:"delta"`
	ItemId       string `json:"itemId"`
	ThreadId     string `json:"threadId"`
	TurnId       string `json:"turnId"`
}

type RequestId = json.RawMessage

type RequestPermissionProfile struct {
	FileSystem *AdditionalFileSystemPermissions `json:"fileSystem,omitempty"`
	Network    *AdditionalNetworkPermissions    `json:"network,omitempty"`
}

type SandboxMode string

const (
	SandboxModeReadOnly         SandboxMode = "read-only"
	SandboxModeWorkspaceWrite   SandboxMode = "workspace-write"
	SandboxModeDangerFullAccess SandboxMode = "danger-full-access"
)

type SandboxPolicy = json.RawMessage

type ServerRequestResolvedNotification struct {
	RequestId RequestId `json:"requestId"`
	ThreadId  string    `json:"threadId"`
}

type ServiceTier string

const (
	ServiceTierFast ServiceTier = "fast"
	ServiceTierFlex ServiceTier = "flex"
)

type SessionSource = json.RawMessage

type SkillsChangedNotification map[string]any

type SubAgentSource = json.RawMessage

type TerminalInteractionNotification struct {
	ItemId    string `json:"itemId"`
	ProcessId string `json:"processId"`
	Stdin     string `json:"stdin"`
	ThreadId  string `json:"threadId"`
	TurnId    string `json:"turnId"`
}

type TextElement struct {
	ByteRange   ByteRange `json:"byteRange"`
	Placeholder *string   `json:"placeholder,omitempty"`
}

type TextPosition struct {
	Column uint64 `json:"column"`
	Line   uint64 `json:"line"`
}

type TextRange struct {
	End   TextPosition `json:"end"`
	Start TextPosition `json:"start"`
}

type Thread struct {
	AgentNickname *string       `json:"agentNickname,omitempty"`
	AgentRole     *string       `json:"agentRole,omitempty"`
	CliVersion    string        `json:"cliVersion"`
	CreatedAt     int64         `json:"createdAt"`
	CWD           string        `json:"cwd"`
	Ephemeral     bool          `json:"ephemeral"`
	GitInfo       *GitInfo      `json:"gitInfo,omitempty"`
	ID            string        `json:"id"`
	ModelProvider string        `json:"modelProvider"`
	Name          *string       `json:"name,omitempty"`
	Path          *string       `json:"path,omitempty"`
	Preview       string        `json:"preview"`
	Source        SessionSource `json:"source"`
	Status        ThreadStatus  `json:"status"`
	Turns         []Turn        `json:"turns"`
	UpdatedAt     int64         `json:"updatedAt"`
}

type ThreadActiveFlag string

const (
	ThreadActiveFlagWaitingOnApproval  ThreadActiveFlag = "waitingOnApproval"
	ThreadActiveFlagWaitingOnUserInput ThreadActiveFlag = "waitingOnUserInput"
)

type ThreadArchiveParams struct {
	ThreadId string `json:"threadId"`
}

type ThreadArchiveResponse map[string]any

type ThreadArchivedNotification struct {
	ThreadId string `json:"threadId"`
}

type ThreadClosedNotification struct {
	ThreadId string `json:"threadId"`
}

type ThreadCompactStartParams struct {
	ThreadId string `json:"threadId"`
}

type ThreadCompactStartResponse map[string]any

type ThreadForkParams struct {
	ApprovalPolicy        *AskForApproval    `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer     *ApprovalsReviewer `json:"approvalsReviewer,omitempty"`
	BaseInstructions      *string            `json:"baseInstructions,omitempty"`
	Config                map[string]any     `json:"config,omitempty"`
	CWD                   *string            `json:"cwd,omitempty"`
	DeveloperInstructions *string            `json:"developerInstructions,omitempty"`
	Ephemeral             *bool              `json:"ephemeral,omitempty"`
	Model                 *string            `json:"model,omitempty"`
	ModelProvider         *string            `json:"modelProvider,omitempty"`
	Sandbox               *SandboxMode       `json:"sandbox,omitempty"`
	ServiceTier           *ServiceTier       `json:"serviceTier,omitempty"`
	ThreadId              string             `json:"threadId"`
}

type ThreadForkResponse struct {
	ApprovalPolicy    AskForApproval    `json:"approvalPolicy"`
	ApprovalsReviewer ApprovalsReviewer `json:"approvalsReviewer"`
	CWD               string            `json:"cwd"`
	Model             string            `json:"model"`
	ModelProvider     string            `json:"modelProvider"`
	ReasoningEffort   *ReasoningEffort  `json:"reasoningEffort,omitempty"`
	Sandbox           SandboxPolicy     `json:"sandbox"`
	ServiceTier       *ServiceTier      `json:"serviceTier,omitempty"`
	Thread            Thread            `json:"thread"`
}

type ThreadId string

type ThreadItem = json.RawMessage

type ThreadListParams struct {
	Archived       *bool              `json:"archived,omitempty"`
	Cursor         *string            `json:"cursor,omitempty"`
	CWD            *string            `json:"cwd,omitempty"`
	Limit          *uint32            `json:"limit,omitempty"`
	ModelProviders []string           `json:"modelProviders,omitempty"`
	SearchTerm     *string            `json:"searchTerm,omitempty"`
	SortKey        *ThreadSortKey     `json:"sortKey,omitempty"`
	SourceKinds    []ThreadSourceKind `json:"sourceKinds,omitempty"`
}

type ThreadListResponse struct {
	Data       []Thread `json:"data"`
	NextCursor *string  `json:"nextCursor,omitempty"`
}

type ThreadNameUpdatedNotification struct {
	ThreadId   string  `json:"threadId"`
	ThreadName *string `json:"threadName,omitempty"`
}

type ThreadReadParams struct {
	IncludeTurns *bool  `json:"includeTurns,omitempty"`
	ThreadId     string `json:"threadId"`
}

type ThreadReadResponse struct {
	Thread Thread `json:"thread"`
}

type ThreadRealtimeAudioChunk struct {
	Data              string  `json:"data"`
	ItemId            *string `json:"itemId,omitempty"`
	NumChannels       uint16  `json:"numChannels"`
	SampleRate        uint32  `json:"sampleRate"`
	SamplesPerChannel *uint32 `json:"samplesPerChannel,omitempty"`
}

type ThreadRealtimeClosedNotification struct {
	Reason   *string `json:"reason,omitempty"`
	ThreadId string  `json:"threadId"`
}

type ThreadRealtimeErrorNotification struct {
	Message  string `json:"message"`
	ThreadId string `json:"threadId"`
}

type ThreadRealtimeItemAddedNotification struct {
	Item     any    `json:"item"`
	ThreadId string `json:"threadId"`
}

type ThreadRealtimeOutputAudioDeltaNotification struct {
	Audio    ThreadRealtimeAudioChunk `json:"audio"`
	ThreadId string                   `json:"threadId"`
}

type ThreadRealtimeStartedNotification struct {
	SessionId *string `json:"sessionId,omitempty"`
	ThreadId  string  `json:"threadId"`
}

type ThreadResumeParams struct {
	ApprovalPolicy        *AskForApproval    `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer     *ApprovalsReviewer `json:"approvalsReviewer,omitempty"`
	BaseInstructions      *string            `json:"baseInstructions,omitempty"`
	Config                map[string]any     `json:"config,omitempty"`
	CWD                   *string            `json:"cwd,omitempty"`
	DeveloperInstructions *string            `json:"developerInstructions,omitempty"`
	Model                 *string            `json:"model,omitempty"`
	ModelProvider         *string            `json:"modelProvider,omitempty"`
	Personality           *Personality       `json:"personality,omitempty"`
	Sandbox               *SandboxMode       `json:"sandbox,omitempty"`
	ServiceTier           *ServiceTier       `json:"serviceTier,omitempty"`
	ThreadId              string             `json:"threadId"`
}

type ThreadResumeResponse struct {
	ApprovalPolicy    AskForApproval    `json:"approvalPolicy"`
	ApprovalsReviewer ApprovalsReviewer `json:"approvalsReviewer"`
	CWD               string            `json:"cwd"`
	Model             string            `json:"model"`
	ModelProvider     string            `json:"modelProvider"`
	ReasoningEffort   *ReasoningEffort  `json:"reasoningEffort,omitempty"`
	Sandbox           SandboxPolicy     `json:"sandbox"`
	ServiceTier       *ServiceTier      `json:"serviceTier,omitempty"`
	Thread            Thread            `json:"thread"`
}

type ThreadSetNameParams struct {
	Name     string `json:"name"`
	ThreadId string `json:"threadId"`
}

type ThreadSetNameResponse map[string]any

type ThreadSortKey string

const (
	ThreadSortKeyCreatedAt ThreadSortKey = "created_at"
	ThreadSortKeyUpdatedAt ThreadSortKey = "updated_at"
)

type ThreadSourceKind string

const (
	ThreadSourceKindCLI                 ThreadSourceKind = "cli"
	ThreadSourceKindVscode              ThreadSourceKind = "vscode"
	ThreadSourceKindExec                ThreadSourceKind = "exec"
	ThreadSourceKindAppServer           ThreadSourceKind = "appServer"
	ThreadSourceKindSubAgent            ThreadSourceKind = "subAgent"
	ThreadSourceKindSubAgentReview      ThreadSourceKind = "subAgentReview"
	ThreadSourceKindSubAgentCompact     ThreadSourceKind = "subAgentCompact"
	ThreadSourceKindSubAgentThreadSpawn ThreadSourceKind = "subAgentThreadSpawn"
	ThreadSourceKindSubAgentOther       ThreadSourceKind = "subAgentOther"
	ThreadSourceKindUnknown             ThreadSourceKind = "unknown"
)

type ThreadStartParams struct {
	ApprovalPolicy        *AskForApproval    `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer     *ApprovalsReviewer `json:"approvalsReviewer,omitempty"`
	BaseInstructions      *string            `json:"baseInstructions,omitempty"`
	Config                map[string]any     `json:"config,omitempty"`
	CWD                   *string            `json:"cwd,omitempty"`
	DeveloperInstructions *string            `json:"developerInstructions,omitempty"`
	Ephemeral             *bool              `json:"ephemeral,omitempty"`
	Model                 *string            `json:"model,omitempty"`
	ModelProvider         *string            `json:"modelProvider,omitempty"`
	Personality           *Personality       `json:"personality,omitempty"`
	Sandbox               *SandboxMode       `json:"sandbox,omitempty"`
	ServiceName           *string            `json:"serviceName,omitempty"`
	ServiceTier           *ServiceTier       `json:"serviceTier,omitempty"`
}

type ThreadStartResponse struct {
	ApprovalPolicy    AskForApproval    `json:"approvalPolicy"`
	ApprovalsReviewer ApprovalsReviewer `json:"approvalsReviewer"`
	CWD               string            `json:"cwd"`
	Model             string            `json:"model"`
	ModelProvider     string            `json:"modelProvider"`
	ReasoningEffort   *ReasoningEffort  `json:"reasoningEffort,omitempty"`
	Sandbox           SandboxPolicy     `json:"sandbox"`
	ServiceTier       *ServiceTier      `json:"serviceTier,omitempty"`
	Thread            Thread            `json:"thread"`
}

type ThreadStartedNotification struct {
	Thread Thread `json:"thread"`
}

type ThreadStatus = json.RawMessage

type ThreadStatusChangedNotification struct {
	Status   ThreadStatus `json:"status"`
	ThreadId string       `json:"threadId"`
}

type ThreadTokenUsage struct {
	Last               TokenUsageBreakdown `json:"last"`
	ModelContextWindow *int64              `json:"modelContextWindow,omitempty"`
	Total              TokenUsageBreakdown `json:"total"`
}

type ThreadTokenUsageUpdatedNotification struct {
	ThreadId   string           `json:"threadId"`
	TokenUsage ThreadTokenUsage `json:"tokenUsage"`
	TurnId     string           `json:"turnId"`
}

type ThreadUnarchiveParams struct {
	ThreadId string `json:"threadId"`
}

type ThreadUnarchiveResponse struct {
	Thread Thread `json:"thread"`
}

type ThreadUnarchivedNotification struct {
	ThreadId string `json:"threadId"`
}

type TokenUsageBreakdown struct {
	CachedInputTokens     int64 `json:"cachedInputTokens"`
	InputTokens           int64 `json:"inputTokens"`
	OutputTokens          int64 `json:"outputTokens"`
	ReasoningOutputTokens int64 `json:"reasoningOutputTokens"`
	TotalTokens           int64 `json:"totalTokens"`
}

type ToolRequestUserInputOption struct {
	Description string `json:"description"`
	Label       string `json:"label"`
}

type ToolRequestUserInputParams struct {
	ItemId    string                         `json:"itemId"`
	Questions []ToolRequestUserInputQuestion `json:"questions"`
	ThreadId  string                         `json:"threadId"`
	TurnId    string                         `json:"turnId"`
}

type ToolRequestUserInputQuestion struct {
	Header   string                       `json:"header"`
	ID       string                       `json:"id"`
	IsOther  *bool                        `json:"isOther,omitempty"`
	IsSecret *bool                        `json:"isSecret,omitempty"`
	Options  []ToolRequestUserInputOption `json:"options,omitempty"`
	Question string                       `json:"question"`
}

type Turn struct {
	Error  *TurnError   `json:"error,omitempty"`
	ID     string       `json:"id"`
	Items  []ThreadItem `json:"items"`
	Status TurnStatus   `json:"status"`
}

type TurnCompletedNotification struct {
	ThreadId string `json:"threadId"`
	Turn     Turn   `json:"turn"`
}

type TurnDiffUpdatedNotification struct {
	Diff     string `json:"diff"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type TurnError struct {
	AdditionalDetails *string         `json:"additionalDetails,omitempty"`
	CodexErrorInfo    *CodexErrorInfo `json:"codexErrorInfo,omitempty"`
	Message           string          `json:"message"`
}

type TurnInterruptParams struct {
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type TurnInterruptResponse map[string]any

type TurnPlanStep struct {
	Status TurnPlanStepStatus `json:"status"`
	Step   string             `json:"step"`
}

type TurnPlanStepStatus string

const (
	TurnPlanStepStatusPending    TurnPlanStepStatus = "pending"
	TurnPlanStepStatusInProgress TurnPlanStepStatus = "inProgress"
	TurnPlanStepStatusCompleted  TurnPlanStepStatus = "completed"
)

type TurnPlanUpdatedNotification struct {
	Explanation *string        `json:"explanation,omitempty"`
	Plan        []TurnPlanStep `json:"plan"`
	ThreadId    string         `json:"threadId"`
	TurnId      string         `json:"turnId"`
}

type TurnStartParams struct {
	ApprovalPolicy    *AskForApproval    `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer *ApprovalsReviewer `json:"approvalsReviewer,omitempty"`
	CWD               *string            `json:"cwd,omitempty"`
	Effort            *ReasoningEffort   `json:"effort,omitempty"`
	Input             []UserInput        `json:"input"`
	Model             *string            `json:"model,omitempty"`
	OutputSchema      json.RawMessage    `json:"outputSchema,omitempty"`
	Personality       *Personality       `json:"personality,omitempty"`
	SandboxPolicy     *SandboxPolicy     `json:"sandboxPolicy,omitempty"`
	ServiceTier       *ServiceTier       `json:"serviceTier,omitempty"`
	Summary           *ReasoningSummary  `json:"summary,omitempty"`
	ThreadId          string             `json:"threadId"`
}

type TurnStartResponse struct {
	Turn Turn `json:"turn"`
}

type TurnStartedNotification struct {
	ThreadId string `json:"threadId"`
	Turn     Turn   `json:"turn"`
}

type TurnStatus string

const (
	TurnStatusCompleted   TurnStatus = "completed"
	TurnStatusInterrupted TurnStatus = "interrupted"
	TurnStatusFailed      TurnStatus = "failed"
	TurnStatusInProgress  TurnStatus = "inProgress"
)

type TurnSteerParams struct {
	ExpectedTurnId string      `json:"expectedTurnId"`
	Input          []UserInput `json:"input"`
	ThreadId       string      `json:"threadId"`
}

type TurnSteerResponse struct {
	TurnId string `json:"turnId"`
}

type UserInput = json.RawMessage

type WebSearchAction = json.RawMessage

type WindowsSandboxSetupCompletedNotification struct {
	Error   *string                 `json:"error,omitempty"`
	Mode    WindowsSandboxSetupMode `json:"mode"`
	Success bool                    `json:"success"`
}

type WindowsSandboxSetupMode string

const (
	WindowsSandboxSetupModeElevated   WindowsSandboxSetupMode = "elevated"
	WindowsSandboxSetupModeUnelevated WindowsSandboxSetupMode = "unelevated"
)

type WindowsWorldWritableWarningNotification struct {
	ExtraCount  uint64   `json:"extraCount"`
	FailedScan  bool     `json:"failedScan"`
	SamplePaths []string `json:"samplePaths"`
}

type V2AbsolutePathBuf any

type V2CommandAction any

type V2ThreadId any
