// Code generated by cmd/updatesdkartifacts; DO NOT EDIT.

package protocol

import "encoding/json"

type AbsolutePathBuf string

type AccountLoginCompletedNotification struct {
	Error   *string `json:"error,omitempty"`
	LoginId *string `json:"loginId,omitempty"`
	Success bool    `json:"success"`
}

type AccountRateLimitsUpdatedNotification struct {
	RateLimits RateLimitSnapshot `json:"rateLimits"`
}

type AccountUpdatedNotification struct {
	AuthMode *AuthMode `json:"authMode,omitempty"`
	PlanType *PlanType `json:"planType,omitempty"`
}

type AdditionalFileSystemPermissions struct {
	Read  []V2AbsolutePathBuf `json:"read,omitempty"`
	Write []V2AbsolutePathBuf `json:"write,omitempty"`
}

type AdditionalNetworkPermissions struct {
	Enabled *bool `json:"enabled,omitempty"`
}

type AgentMessageDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemId   string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type AgentPath string

type AppBranding struct {
	Category          *string `json:"category,omitempty"`
	Developer         *string `json:"developer,omitempty"`
	IsDiscoverableApp bool    `json:"isDiscoverableApp"`
	PrivacyPolicy     *string `json:"privacyPolicy,omitempty"`
	TermsOfService    *string `json:"termsOfService,omitempty"`
	Website           *string `json:"website,omitempty"`
}

type AppInfo struct {
	AppMetadata         *AppMetadata      `json:"appMetadata,omitempty"`
	Branding            *AppBranding      `json:"branding,omitempty"`
	Description         *string           `json:"description,omitempty"`
	DistributionChannel *string           `json:"distributionChannel,omitempty"`
	ID                  string            `json:"id"`
	InstallUrl          *string           `json:"installUrl,omitempty"`
	IsAccessible        *bool             `json:"isAccessible,omitempty"`
	IsEnabled           *bool             `json:"isEnabled,omitempty"`
	Labels              map[string]string `json:"labels,omitempty"`
	LogoUrl             *string           `json:"logoUrl,omitempty"`
	LogoUrlDark         *string           `json:"logoUrlDark,omitempty"`
	Name                string            `json:"name"`
	PluginDisplayNames  []string          `json:"pluginDisplayNames,omitempty"`
}

type AppListUpdatedNotification struct {
	Data []AppInfo `json:"data"`
}

type AppMetadata struct {
	Categories                 []string        `json:"categories,omitempty"`
	Developer                  *string         `json:"developer,omitempty"`
	FirstPartyRequiresInstall  *bool           `json:"firstPartyRequiresInstall,omitempty"`
	FirstPartyType             *string         `json:"firstPartyType,omitempty"`
	Review                     *AppReview      `json:"review,omitempty"`
	Screenshots                []AppScreenshot `json:"screenshots,omitempty"`
	SeoDescription             *string         `json:"seoDescription,omitempty"`
	ShowInComposerWhenUnlinked *bool           `json:"showInComposerWhenUnlinked,omitempty"`
	SubCategories              []string        `json:"subCategories,omitempty"`
	Version                    *string         `json:"version,omitempty"`
	VersionId                  *string         `json:"versionId,omitempty"`
	VersionNotes               *string         `json:"versionNotes,omitempty"`
}

type AppReview struct {
	Status string `json:"status"`
}

type AppScreenshot struct {
	FileId     *string `json:"fileId,omitempty"`
	URL        *string `json:"url,omitempty"`
	UserPrompt string  `json:"userPrompt"`
}

type ApplyPatchApprovalParams struct {
	CallId         string                `json:"callId"`
	ConversationId V2ThreadId            `json:"conversationId"`
	FileChanges    map[string]FileChange `json:"fileChanges"`
	GrantRoot      *string               `json:"grantRoot,omitempty"`
	Reason         *string               `json:"reason,omitempty"`
}

type ApprovalsReviewer string

const (
	ApprovalsReviewerUser             ApprovalsReviewer = "user"
	ApprovalsReviewerGuardianSubagent ApprovalsReviewer = "guardian_subagent"
)

var approvalsReviewerValues = map[string]ApprovalsReviewer{
	"user":              ApprovalsReviewerUser,
	"guardian_subagent": ApprovalsReviewerGuardianSubagent,
}

func ParseApprovalsReviewer(value string) (ApprovalsReviewer, bool) {
	return parseStringEnum[ApprovalsReviewer](value, approvalsReviewerValues)
}

func (v ApprovalsReviewer) IsValid() bool {
	return isValidStringEnum(v, approvalsReviewerValues)
}

type AskForApprovalGranular struct {
	MCPElicitations    bool  `json:"mcp_elicitations"`
	RequestPermissions *bool `json:"request_permissions,omitempty"`
	Rules              bool  `json:"rules"`
	SandboxApproval    bool  `json:"sandbox_approval"`
	SkillApproval      *bool `json:"skill_approval,omitempty"`
}

type AskForApprovalKind string

const (
	AskForApprovalKindNever     AskForApprovalKind = "never"
	AskForApprovalKindOnFailure AskForApprovalKind = "on-failure"
	AskForApprovalKindOnRequest AskForApprovalKind = "on-request"
	AskForApprovalKindUntrusted AskForApprovalKind = "untrusted"
)

var askForApprovalKindValues = map[string]AskForApprovalKind{
	"never":      AskForApprovalKindNever,
	"on-failure": AskForApprovalKindOnFailure,
	"on-request": AskForApprovalKindOnRequest,
	"untrusted":  AskForApprovalKindUntrusted,
}

func ParseAskForApprovalKind(value string) (AskForApprovalKind, bool) {
	return parseStringEnum[AskForApprovalKind](value, askForApprovalKindValues)
}

func (v AskForApprovalKind) IsValid() bool {
	return isValidStringEnum(v, askForApprovalKindValues)
}

type AskForApproval struct {
	Kind     AskForApprovalKind      `json:"-"`
	Granular *AskForApprovalGranular `json:"-"`
}

func (v AskForApproval) MarshalJSON() ([]byte, error) {
	return marshalStringOrSingleFieldObjectUnion(v.Kind,
		objectUnionField{name: "granular", value: v.Granular},
	)
}

func (v *AskForApproval) UnmarshalJSON(data []byte) error {
	*v = AskForApproval{}
	kind, err := unmarshalStringOrSingleFieldObjectUnion[AskForApprovalKind](data, askForApprovalKindValues, map[string]func(json.RawMessage) error{
		"granular": func(raw json.RawMessage) error {
			var payload AskForApprovalGranular
			if err := json.Unmarshal(raw, &payload); err != nil {
				return err
			}
			v.Granular = &payload
			return nil
		},
	})
	if err != nil {
		return err
	}
	v.Kind = kind
	return nil
}

type AuthMode string

const (
	AuthModeApikey            AuthMode = "apikey"
	AuthModeChatgpt           AuthMode = "chatgpt"
	AuthModeChatgptAuthTokens AuthMode = "chatgptAuthTokens"
)

var authModeValues = map[string]AuthMode{
	"apikey":            AuthModeApikey,
	"chatgpt":           AuthModeChatgpt,
	"chatgptAuthTokens": AuthModeChatgptAuthTokens,
}

func ParseAuthMode(value string) (AuthMode, bool) {
	return parseStringEnum[AuthMode](value, authModeValues)
}

func (v AuthMode) IsValid() bool {
	return isValidStringEnum(v, authModeValues)
}

type ByteRange struct {
	End   uint64 `json:"end"`
	Start uint64 `json:"start"`
}

type ChatgptAuthTokensRefreshParams struct {
	PreviousAccountId *string                        `json:"previousAccountId,omitempty"`
	Reason            ChatgptAuthTokensRefreshReason `json:"reason"`
}

type ChatgptAuthTokensRefreshReason string

const ChatgptAuthTokensRefreshReasonUnauthorized ChatgptAuthTokensRefreshReason = "unauthorized"

var chatgptAuthTokensRefreshReasonValues = map[string]ChatgptAuthTokensRefreshReason{
	"unauthorized": ChatgptAuthTokensRefreshReasonUnauthorized,
}

func ParseChatgptAuthTokensRefreshReason(value string) (ChatgptAuthTokensRefreshReason, bool) {
	return parseStringEnum[ChatgptAuthTokensRefreshReason](value, chatgptAuthTokensRefreshReasonValues)
}

func (v ChatgptAuthTokensRefreshReason) IsValid() bool {
	return isValidStringEnum(v, chatgptAuthTokensRefreshReasonValues)
}

type ClientInfo struct {
	Name    string  `json:"name"`
	Title   *string `json:"title,omitempty"`
	Version string  `json:"version"`
}

type CodexErrorInfoActiveTurnNotSteerable struct {
	TurnKind NonSteerableTurnKind `json:"turnKind"`
}

type CodexErrorInfoHttpConnectionFailed struct {
	HttpStatusCode *uint16 `json:"httpStatusCode,omitempty"`
}

type CodexErrorInfoResponseStreamConnectionFailed struct {
	HttpStatusCode *uint16 `json:"httpStatusCode,omitempty"`
}

type CodexErrorInfoResponseStreamDisconnected struct {
	HttpStatusCode *uint16 `json:"httpStatusCode,omitempty"`
}

type CodexErrorInfoResponseTooManyFailedAttempts struct {
	HttpStatusCode *uint16 `json:"httpStatusCode,omitempty"`
}

type CodexErrorInfoKind string

const (
	CodexErrorInfoKindBadRequest            CodexErrorInfoKind = "badRequest"
	CodexErrorInfoKindContextWindowExceeded CodexErrorInfoKind = "contextWindowExceeded"
	CodexErrorInfoKindInternalServerError   CodexErrorInfoKind = "internalServerError"
	CodexErrorInfoKindOther                 CodexErrorInfoKind = "other"
	CodexErrorInfoKindSandboxError          CodexErrorInfoKind = "sandboxError"
	CodexErrorInfoKindServerOverloaded      CodexErrorInfoKind = "serverOverloaded"
	CodexErrorInfoKindThreadRollbackFailed  CodexErrorInfoKind = "threadRollbackFailed"
	CodexErrorInfoKindUnauthorized          CodexErrorInfoKind = "unauthorized"
	CodexErrorInfoKindUsageLimitExceeded    CodexErrorInfoKind = "usageLimitExceeded"
)

var codexErrorInfoKindValues = map[string]CodexErrorInfoKind{
	"badRequest":            CodexErrorInfoKindBadRequest,
	"contextWindowExceeded": CodexErrorInfoKindContextWindowExceeded,
	"internalServerError":   CodexErrorInfoKindInternalServerError,
	"other":                 CodexErrorInfoKindOther,
	"sandboxError":          CodexErrorInfoKindSandboxError,
	"serverOverloaded":      CodexErrorInfoKindServerOverloaded,
	"threadRollbackFailed":  CodexErrorInfoKindThreadRollbackFailed,
	"unauthorized":          CodexErrorInfoKindUnauthorized,
	"usageLimitExceeded":    CodexErrorInfoKindUsageLimitExceeded,
}

func ParseCodexErrorInfoKind(value string) (CodexErrorInfoKind, bool) {
	return parseStringEnum[CodexErrorInfoKind](value, codexErrorInfoKindValues)
}

func (v CodexErrorInfoKind) IsValid() bool {
	return isValidStringEnum(v, codexErrorInfoKindValues)
}

type CodexErrorInfo struct {
	Kind                           CodexErrorInfoKind                            `json:"-"`
	ActiveTurnNotSteerable         *CodexErrorInfoActiveTurnNotSteerable         `json:"-"`
	HttpConnectionFailed           *CodexErrorInfoHttpConnectionFailed           `json:"-"`
	ResponseStreamConnectionFailed *CodexErrorInfoResponseStreamConnectionFailed `json:"-"`
	ResponseStreamDisconnected     *CodexErrorInfoResponseStreamDisconnected     `json:"-"`
	ResponseTooManyFailedAttempts  *CodexErrorInfoResponseTooManyFailedAttempts  `json:"-"`
}

func (v CodexErrorInfo) MarshalJSON() ([]byte, error) {
	return marshalStringOrSingleFieldObjectUnion(v.Kind,
		objectUnionField{name: "activeTurnNotSteerable", value: v.ActiveTurnNotSteerable},
		objectUnionField{name: "httpConnectionFailed", value: v.HttpConnectionFailed},
		objectUnionField{name: "responseStreamConnectionFailed", value: v.ResponseStreamConnectionFailed},
		objectUnionField{name: "responseStreamDisconnected", value: v.ResponseStreamDisconnected},
		objectUnionField{name: "responseTooManyFailedAttempts", value: v.ResponseTooManyFailedAttempts},
	)
}

func (v *CodexErrorInfo) UnmarshalJSON(data []byte) error {
	*v = CodexErrorInfo{}
	kind, err := unmarshalStringOrSingleFieldObjectUnion[CodexErrorInfoKind](data, codexErrorInfoKindValues, map[string]func(json.RawMessage) error{
		"activeTurnNotSteerable": func(raw json.RawMessage) error {
			var payload CodexErrorInfoActiveTurnNotSteerable
			if err := json.Unmarshal(raw, &payload); err != nil {
				return err
			}
			v.ActiveTurnNotSteerable = &payload
			return nil
		},
		"httpConnectionFailed": func(raw json.RawMessage) error {
			var payload CodexErrorInfoHttpConnectionFailed
			if err := json.Unmarshal(raw, &payload); err != nil {
				return err
			}
			v.HttpConnectionFailed = &payload
			return nil
		},
		"responseStreamConnectionFailed": func(raw json.RawMessage) error {
			var payload CodexErrorInfoResponseStreamConnectionFailed
			if err := json.Unmarshal(raw, &payload); err != nil {
				return err
			}
			v.ResponseStreamConnectionFailed = &payload
			return nil
		},
		"responseStreamDisconnected": func(raw json.RawMessage) error {
			var payload CodexErrorInfoResponseStreamDisconnected
			if err := json.Unmarshal(raw, &payload); err != nil {
				return err
			}
			v.ResponseStreamDisconnected = &payload
			return nil
		},
		"responseTooManyFailedAttempts": func(raw json.RawMessage) error {
			var payload CodexErrorInfoResponseTooManyFailedAttempts
			if err := json.Unmarshal(raw, &payload); err != nil {
				return err
			}
			v.ResponseTooManyFailedAttempts = &payload
			return nil
		},
	})
	if err != nil {
		return err
	}
	v.Kind = kind
	return nil
}

type CollabAgentState struct {
	Message *string           `json:"message,omitempty"`
	Status  CollabAgentStatus `json:"status"`
}

type CollabAgentStatus string

const (
	CollabAgentStatusPendingInit CollabAgentStatus = "pendingInit"
	CollabAgentStatusRunning     CollabAgentStatus = "running"
	CollabAgentStatusInterrupted CollabAgentStatus = "interrupted"
	CollabAgentStatusCompleted   CollabAgentStatus = "completed"
	CollabAgentStatusErrored     CollabAgentStatus = "errored"
	CollabAgentStatusShutdown    CollabAgentStatus = "shutdown"
	CollabAgentStatusNotFound    CollabAgentStatus = "notFound"
)

var collabAgentStatusValues = map[string]CollabAgentStatus{
	"pendingInit": CollabAgentStatusPendingInit,
	"running":     CollabAgentStatusRunning,
	"interrupted": CollabAgentStatusInterrupted,
	"completed":   CollabAgentStatusCompleted,
	"errored":     CollabAgentStatusErrored,
	"shutdown":    CollabAgentStatusShutdown,
	"notFound":    CollabAgentStatusNotFound,
}

func ParseCollabAgentStatus(value string) (CollabAgentStatus, bool) {
	return parseStringEnum[CollabAgentStatus](value, collabAgentStatusValues)
}

func (v CollabAgentStatus) IsValid() bool {
	return isValidStringEnum(v, collabAgentStatusValues)
}

type CollabAgentTool string

const (
	CollabAgentToolSpawnAgent  CollabAgentTool = "spawnAgent"
	CollabAgentToolSendInput   CollabAgentTool = "sendInput"
	CollabAgentToolResumeAgent CollabAgentTool = "resumeAgent"
	CollabAgentToolWait        CollabAgentTool = "wait"
	CollabAgentToolCloseAgent  CollabAgentTool = "closeAgent"
)

var collabAgentToolValues = map[string]CollabAgentTool{
	"spawnAgent":  CollabAgentToolSpawnAgent,
	"sendInput":   CollabAgentToolSendInput,
	"resumeAgent": CollabAgentToolResumeAgent,
	"wait":        CollabAgentToolWait,
	"closeAgent":  CollabAgentToolCloseAgent,
}

func ParseCollabAgentTool(value string) (CollabAgentTool, bool) {
	return parseStringEnum[CollabAgentTool](value, collabAgentToolValues)
}

func (v CollabAgentTool) IsValid() bool {
	return isValidStringEnum(v, collabAgentToolValues)
}

type CollabAgentToolCallStatus string

const (
	CollabAgentToolCallStatusInProgress CollabAgentToolCallStatus = "inProgress"
	CollabAgentToolCallStatusCompleted  CollabAgentToolCallStatus = "completed"
	CollabAgentToolCallStatusFailed     CollabAgentToolCallStatus = "failed"
)

var collabAgentToolCallStatusValues = map[string]CollabAgentToolCallStatus{
	"inProgress": CollabAgentToolCallStatusInProgress,
	"completed":  CollabAgentToolCallStatusCompleted,
	"failed":     CollabAgentToolCallStatusFailed,
}

func ParseCollabAgentToolCallStatus(value string) (CollabAgentToolCallStatus, bool) {
	return parseStringEnum[CollabAgentToolCallStatus](value, collabAgentToolCallStatusValues)
}

func (v CollabAgentToolCallStatus) IsValid() bool {
	return isValidStringEnum(v, collabAgentToolCallStatusValues)
}

type CommandActionType string

const (
	CommandActionTypeListFiles CommandActionType = "listFiles"
	CommandActionTypeRead      CommandActionType = "read"
	CommandActionTypeSearch    CommandActionType = "search"
	CommandActionTypeUnknown   CommandActionType = "unknown"
)

var commandActionTypeValues = map[string]CommandActionType{
	"listFiles": CommandActionTypeListFiles,
	"read":      CommandActionTypeRead,
	"search":    CommandActionTypeSearch,
	"unknown":   CommandActionTypeUnknown,
}

func ParseCommandActionType(value string) (CommandActionType, bool) {
	return parseStringEnum[CommandActionType](value, commandActionTypeValues)
}

func (v CommandActionType) IsValid() bool {
	return isValidStringEnum(v, commandActionTypeValues)
}

type CommandAction struct {
	Type    CommandActionType `json:"type"`
	Command string            `json:"command"`
	Name    *string           `json:"name,omitempty"`
	Path    *string           `json:"path,omitempty"`
	Query   *string           `json:"query,omitempty"`
}

type CommandExecOutputDeltaNotification struct {
	CapReached  bool                    `json:"capReached"`
	DeltaBase64 string                  `json:"deltaBase64"`
	ProcessId   string                  `json:"processId"`
	Stream      CommandExecOutputStream `json:"stream"`
}

type CommandExecOutputStream string

const (
	CommandExecOutputStreamStdout CommandExecOutputStream = "stdout"
	CommandExecOutputStreamStderr CommandExecOutputStream = "stderr"
)

var commandExecOutputStreamValues = map[string]CommandExecOutputStream{
	"stdout": CommandExecOutputStreamStdout,
	"stderr": CommandExecOutputStreamStderr,
}

func ParseCommandExecOutputStream(value string) (CommandExecOutputStream, bool) {
	return parseStringEnum[CommandExecOutputStream](value, commandExecOutputStreamValues)
}

func (v CommandExecOutputStream) IsValid() bool {
	return isValidStringEnum(v, commandExecOutputStreamValues)
}

type CommandExecutionOutputDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemId   string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type CommandExecutionRequestApprovalParams struct {
	ApprovalId                      *string                  `json:"approvalId,omitempty"`
	Command                         *string                  `json:"command,omitempty"`
	CommandActions                  []V2CommandAction        `json:"commandActions,omitempty"`
	CWD                             *string                  `json:"cwd,omitempty"`
	ItemId                          string                   `json:"itemId"`
	NetworkApprovalContext          *NetworkApprovalContext  `json:"networkApprovalContext,omitempty"`
	ProposedExecpolicyAmendment     []string                 `json:"proposedExecpolicyAmendment,omitempty"`
	ProposedNetworkPolicyAmendments []NetworkPolicyAmendment `json:"proposedNetworkPolicyAmendments,omitempty"`
	Reason                          *string                  `json:"reason,omitempty"`
	ThreadId                        string                   `json:"threadId"`
	TurnId                          string                   `json:"turnId"`
}

type CommandExecutionSource string

const (
	CommandExecutionSourceAgent                  CommandExecutionSource = "agent"
	CommandExecutionSourceUserShell              CommandExecutionSource = "userShell"
	CommandExecutionSourceUnifiedExecStartup     CommandExecutionSource = "unifiedExecStartup"
	CommandExecutionSourceUnifiedExecInteraction CommandExecutionSource = "unifiedExecInteraction"
)

var commandExecutionSourceValues = map[string]CommandExecutionSource{
	"agent":                  CommandExecutionSourceAgent,
	"userShell":              CommandExecutionSourceUserShell,
	"unifiedExecStartup":     CommandExecutionSourceUnifiedExecStartup,
	"unifiedExecInteraction": CommandExecutionSourceUnifiedExecInteraction,
}

func ParseCommandExecutionSource(value string) (CommandExecutionSource, bool) {
	return parseStringEnum[CommandExecutionSource](value, commandExecutionSourceValues)
}

func (v CommandExecutionSource) IsValid() bool {
	return isValidStringEnum(v, commandExecutionSourceValues)
}

type CommandExecutionStatus string

const (
	CommandExecutionStatusInProgress CommandExecutionStatus = "inProgress"
	CommandExecutionStatusCompleted  CommandExecutionStatus = "completed"
	CommandExecutionStatusFailed     CommandExecutionStatus = "failed"
	CommandExecutionStatusDeclined   CommandExecutionStatus = "declined"
)

var commandExecutionStatusValues = map[string]CommandExecutionStatus{
	"inProgress": CommandExecutionStatusInProgress,
	"completed":  CommandExecutionStatusCompleted,
	"failed":     CommandExecutionStatusFailed,
	"declined":   CommandExecutionStatusDeclined,
}

func ParseCommandExecutionStatus(value string) (CommandExecutionStatus, bool) {
	return parseStringEnum[CommandExecutionStatus](value, commandExecutionStatusValues)
}

func (v CommandExecutionStatus) IsValid() bool {
	return isValidStringEnum(v, commandExecutionStatusValues)
}

type ConfigWarningNotification struct {
	Details *string    `json:"details,omitempty"`
	Path    *string    `json:"path,omitempty"`
	Range   *TextRange `json:"range,omitempty"`
	Summary string     `json:"summary"`
}

type ContextCompactedNotification struct {
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type CreditsSnapshot struct {
	Balance    *string `json:"balance,omitempty"`
	HasCredits bool    `json:"hasCredits"`
	Unlimited  bool    `json:"unlimited"`
}

type DeprecationNoticeNotification struct {
	Details *string `json:"details,omitempty"`
	Summary string  `json:"summary"`
}

type DynamicToolCallOutputContentItemType string

const (
	DynamicToolCallOutputContentItemTypeInputImage DynamicToolCallOutputContentItemType = "inputImage"
	DynamicToolCallOutputContentItemTypeInputText  DynamicToolCallOutputContentItemType = "inputText"
)

var dynamicToolCallOutputContentItemTypeValues = map[string]DynamicToolCallOutputContentItemType{
	"inputImage": DynamicToolCallOutputContentItemTypeInputImage,
	"inputText":  DynamicToolCallOutputContentItemTypeInputText,
}

func ParseDynamicToolCallOutputContentItemType(value string) (DynamicToolCallOutputContentItemType, bool) {
	return parseStringEnum[DynamicToolCallOutputContentItemType](value, dynamicToolCallOutputContentItemTypeValues)
}

func (v DynamicToolCallOutputContentItemType) IsValid() bool {
	return isValidStringEnum(v, dynamicToolCallOutputContentItemTypeValues)
}

type DynamicToolCallOutputContentItem struct {
	Type     DynamicToolCallOutputContentItemType `json:"type"`
	ImageUrl *string                              `json:"imageUrl,omitempty"`
	Text     *string                              `json:"text,omitempty"`
}

type DynamicToolCallParams struct {
	Arguments any    `json:"arguments"`
	CallId    string `json:"callId"`
	ThreadId  string `json:"threadId"`
	Tool      string `json:"tool"`
	TurnId    string `json:"turnId"`
}

type DynamicToolCallStatus string

const (
	DynamicToolCallStatusInProgress DynamicToolCallStatus = "inProgress"
	DynamicToolCallStatusCompleted  DynamicToolCallStatus = "completed"
	DynamicToolCallStatusFailed     DynamicToolCallStatus = "failed"
)

var dynamicToolCallStatusValues = map[string]DynamicToolCallStatus{
	"inProgress": DynamicToolCallStatusInProgress,
	"completed":  DynamicToolCallStatusCompleted,
	"failed":     DynamicToolCallStatusFailed,
}

func ParseDynamicToolCallStatus(value string) (DynamicToolCallStatus, bool) {
	return parseStringEnum[DynamicToolCallStatus](value, dynamicToolCallStatusValues)
}

func (v DynamicToolCallStatus) IsValid() bool {
	return isValidStringEnum(v, dynamicToolCallStatusValues)
}

type ErrorNotification struct {
	Error     TurnError `json:"error"`
	ThreadId  string    `json:"threadId"`
	TurnId    string    `json:"turnId"`
	WillRetry bool      `json:"willRetry"`
}

type ExecCommandApprovalParams struct {
	ApprovalId     *string         `json:"approvalId,omitempty"`
	CallId         string          `json:"callId"`
	Command        []string        `json:"command"`
	ConversationId V2ThreadId      `json:"conversationId"`
	CWD            string          `json:"cwd"`
	ParsedCmd      []ParsedCommand `json:"parsedCmd"`
	Reason         *string         `json:"reason,omitempty"`
}

type FileChangeType string

const (
	FileChangeTypeAdd    FileChangeType = "add"
	FileChangeTypeDelete FileChangeType = "delete"
	FileChangeTypeUpdate FileChangeType = "update"
)

var fileChangeTypeValues = map[string]FileChangeType{
	"add":    FileChangeTypeAdd,
	"delete": FileChangeTypeDelete,
	"update": FileChangeTypeUpdate,
}

func ParseFileChangeType(value string) (FileChangeType, bool) {
	return parseStringEnum[FileChangeType](value, fileChangeTypeValues)
}

func (v FileChangeType) IsValid() bool {
	return isValidStringEnum(v, fileChangeTypeValues)
}

type FileChange struct {
	Type        FileChangeType `json:"type"`
	Content     *string        `json:"content,omitempty"`
	MovePath    *string        `json:"move_path,omitempty"`
	UnifiedDiff *string        `json:"unified_diff,omitempty"`
}

type FileChangeOutputDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemId   string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type FileChangeRequestApprovalParams struct {
	GrantRoot *string `json:"grantRoot,omitempty"`
	ItemId    string  `json:"itemId"`
	Reason    *string `json:"reason,omitempty"`
	ThreadId  string  `json:"threadId"`
	TurnId    string  `json:"turnId"`
}

type FileUpdateChange struct {
	Diff string          `json:"diff"`
	Kind PatchChangeKind `json:"kind"`
	Path string          `json:"path"`
}

type FsChangedNotification struct {
	ChangedPaths []AbsolutePathBuf `json:"changedPaths"`
	WatchId      string            `json:"watchId"`
}

type FuzzyFileSearchMatchType string

const (
	FuzzyFileSearchMatchTypeFile      FuzzyFileSearchMatchType = "file"
	FuzzyFileSearchMatchTypeDirectory FuzzyFileSearchMatchType = "directory"
)

var fuzzyFileSearchMatchTypeValues = map[string]FuzzyFileSearchMatchType{
	"file":      FuzzyFileSearchMatchTypeFile,
	"directory": FuzzyFileSearchMatchTypeDirectory,
}

func ParseFuzzyFileSearchMatchType(value string) (FuzzyFileSearchMatchType, bool) {
	return parseStringEnum[FuzzyFileSearchMatchType](value, fuzzyFileSearchMatchTypeValues)
}

func (v FuzzyFileSearchMatchType) IsValid() bool {
	return isValidStringEnum(v, fuzzyFileSearchMatchTypeValues)
}

type FuzzyFileSearchResult struct {
	FileName  string                   `json:"file_name"`
	Indices   []uint32                 `json:"indices,omitempty"`
	MatchType FuzzyFileSearchMatchType `json:"match_type"`
	Path      string                   `json:"path"`
	Root      string                   `json:"root"`
	Score     uint32                   `json:"score"`
}

type FuzzyFileSearchSessionCompletedNotification struct {
	SessionId string `json:"sessionId"`
}

type FuzzyFileSearchSessionUpdatedNotification struct {
	Files     []FuzzyFileSearchResult `json:"files"`
	Query     string                  `json:"query"`
	SessionId string                  `json:"sessionId"`
}

type GitInfo struct {
	Branch    *string `json:"branch,omitempty"`
	OriginUrl *string `json:"originUrl,omitempty"`
	Sha       *string `json:"sha,omitempty"`
}

type GuardianApprovalReview struct {
	Rationale *string                      `json:"rationale,omitempty"`
	RiskLevel *GuardianRiskLevel           `json:"riskLevel,omitempty"`
	RiskScore *uint64                      `json:"riskScore,omitempty"`
	Status    GuardianApprovalReviewStatus `json:"status"`
}

type GuardianApprovalReviewStatus string

const (
	GuardianApprovalReviewStatusInProgress GuardianApprovalReviewStatus = "inProgress"
	GuardianApprovalReviewStatusApproved   GuardianApprovalReviewStatus = "approved"
	GuardianApprovalReviewStatusDenied     GuardianApprovalReviewStatus = "denied"
	GuardianApprovalReviewStatusAborted    GuardianApprovalReviewStatus = "aborted"
)

var guardianApprovalReviewStatusValues = map[string]GuardianApprovalReviewStatus{
	"inProgress": GuardianApprovalReviewStatusInProgress,
	"approved":   GuardianApprovalReviewStatusApproved,
	"denied":     GuardianApprovalReviewStatusDenied,
	"aborted":    GuardianApprovalReviewStatusAborted,
}

func ParseGuardianApprovalReviewStatus(value string) (GuardianApprovalReviewStatus, bool) {
	return parseStringEnum[GuardianApprovalReviewStatus](value, guardianApprovalReviewStatusValues)
}

func (v GuardianApprovalReviewStatus) IsValid() bool {
	return isValidStringEnum(v, guardianApprovalReviewStatusValues)
}

type GuardianRiskLevel string

const (
	GuardianRiskLevelLow    GuardianRiskLevel = "low"
	GuardianRiskLevelMedium GuardianRiskLevel = "medium"
	GuardianRiskLevelHigh   GuardianRiskLevel = "high"
)

var guardianRiskLevelValues = map[string]GuardianRiskLevel{
	"low":    GuardianRiskLevelLow,
	"medium": GuardianRiskLevelMedium,
	"high":   GuardianRiskLevelHigh,
}

func ParseGuardianRiskLevel(value string) (GuardianRiskLevel, bool) {
	return parseStringEnum[GuardianRiskLevel](value, guardianRiskLevelValues)
}

func (v GuardianRiskLevel) IsValid() bool {
	return isValidStringEnum(v, guardianRiskLevelValues)
}

type HookCompletedNotification struct {
	Run      HookRunSummary `json:"run"`
	ThreadId string         `json:"threadId"`
	TurnId   *string        `json:"turnId,omitempty"`
}

type HookEventName string

const (
	HookEventNamePreToolUse       HookEventName = "preToolUse"
	HookEventNamePostToolUse      HookEventName = "postToolUse"
	HookEventNameSessionStart     HookEventName = "sessionStart"
	HookEventNameUserPromptSubmit HookEventName = "userPromptSubmit"
	HookEventNameStop             HookEventName = "stop"
)

var hookEventNameValues = map[string]HookEventName{
	"preToolUse":       HookEventNamePreToolUse,
	"postToolUse":      HookEventNamePostToolUse,
	"sessionStart":     HookEventNameSessionStart,
	"userPromptSubmit": HookEventNameUserPromptSubmit,
	"stop":             HookEventNameStop,
}

func ParseHookEventName(value string) (HookEventName, bool) {
	return parseStringEnum[HookEventName](value, hookEventNameValues)
}

func (v HookEventName) IsValid() bool {
	return isValidStringEnum(v, hookEventNameValues)
}

type HookExecutionMode string

const (
	HookExecutionModeSync  HookExecutionMode = "sync"
	HookExecutionModeAsync HookExecutionMode = "async"
)

var hookExecutionModeValues = map[string]HookExecutionMode{
	"sync":  HookExecutionModeSync,
	"async": HookExecutionModeAsync,
}

func ParseHookExecutionMode(value string) (HookExecutionMode, bool) {
	return parseStringEnum[HookExecutionMode](value, hookExecutionModeValues)
}

func (v HookExecutionMode) IsValid() bool {
	return isValidStringEnum(v, hookExecutionModeValues)
}

type HookHandlerType string

const (
	HookHandlerTypeCommand HookHandlerType = "command"
	HookHandlerTypePrompt  HookHandlerType = "prompt"
	HookHandlerTypeAgent   HookHandlerType = "agent"
)

var hookHandlerTypeValues = map[string]HookHandlerType{
	"command": HookHandlerTypeCommand,
	"prompt":  HookHandlerTypePrompt,
	"agent":   HookHandlerTypeAgent,
}

func ParseHookHandlerType(value string) (HookHandlerType, bool) {
	return parseStringEnum[HookHandlerType](value, hookHandlerTypeValues)
}

func (v HookHandlerType) IsValid() bool {
	return isValidStringEnum(v, hookHandlerTypeValues)
}

type HookOutputEntry struct {
	Kind HookOutputEntryKind `json:"kind"`
	Text string              `json:"text"`
}

type HookOutputEntryKind string

const (
	HookOutputEntryKindWarning  HookOutputEntryKind = "warning"
	HookOutputEntryKindStop     HookOutputEntryKind = "stop"
	HookOutputEntryKindFeedback HookOutputEntryKind = "feedback"
	HookOutputEntryKindContext  HookOutputEntryKind = "context"
	HookOutputEntryKindError    HookOutputEntryKind = "error"
)

var hookOutputEntryKindValues = map[string]HookOutputEntryKind{
	"warning":  HookOutputEntryKindWarning,
	"stop":     HookOutputEntryKindStop,
	"feedback": HookOutputEntryKindFeedback,
	"context":  HookOutputEntryKindContext,
	"error":    HookOutputEntryKindError,
}

func ParseHookOutputEntryKind(value string) (HookOutputEntryKind, bool) {
	return parseStringEnum[HookOutputEntryKind](value, hookOutputEntryKindValues)
}

func (v HookOutputEntryKind) IsValid() bool {
	return isValidStringEnum(v, hookOutputEntryKindValues)
}

type HookPromptFragment struct {
	HookRunId string `json:"hookRunId"`
	Text      string `json:"text"`
}

type HookRunStatus string

const (
	HookRunStatusRunning   HookRunStatus = "running"
	HookRunStatusCompleted HookRunStatus = "completed"
	HookRunStatusFailed    HookRunStatus = "failed"
	HookRunStatusBlocked   HookRunStatus = "blocked"
	HookRunStatusStopped   HookRunStatus = "stopped"
)

var hookRunStatusValues = map[string]HookRunStatus{
	"running":   HookRunStatusRunning,
	"completed": HookRunStatusCompleted,
	"failed":    HookRunStatusFailed,
	"blocked":   HookRunStatusBlocked,
	"stopped":   HookRunStatusStopped,
}

func ParseHookRunStatus(value string) (HookRunStatus, bool) {
	return parseStringEnum[HookRunStatus](value, hookRunStatusValues)
}

func (v HookRunStatus) IsValid() bool {
	return isValidStringEnum(v, hookRunStatusValues)
}

type HookRunSummary struct {
	CompletedAt   *int64            `json:"completedAt,omitempty"`
	DisplayOrder  int64             `json:"displayOrder"`
	DurationMs    *int64            `json:"durationMs,omitempty"`
	Entries       []HookOutputEntry `json:"entries"`
	EventName     HookEventName     `json:"eventName"`
	ExecutionMode HookExecutionMode `json:"executionMode"`
	HandlerType   HookHandlerType   `json:"handlerType"`
	ID            string            `json:"id"`
	Scope         HookScope         `json:"scope"`
	SourcePath    string            `json:"sourcePath"`
	StartedAt     int64             `json:"startedAt"`
	Status        HookRunStatus     `json:"status"`
	StatusMessage *string           `json:"statusMessage,omitempty"`
}

type HookScope string

const (
	HookScopeThread HookScope = "thread"
	HookScopeTurn   HookScope = "turn"
)

var hookScopeValues = map[string]HookScope{
	"thread": HookScopeThread,
	"turn":   HookScopeTurn,
}

func ParseHookScope(value string) (HookScope, bool) {
	return parseStringEnum[HookScope](value, hookScopeValues)
}

func (v HookScope) IsValid() bool {
	return isValidStringEnum(v, hookScopeValues)
}

type HookStartedNotification struct {
	Run      HookRunSummary `json:"run"`
	ThreadId string         `json:"threadId"`
	TurnId   *string        `json:"turnId,omitempty"`
}

type InitializeCapabilities struct {
	ExperimentalApi           *bool    `json:"experimentalApi,omitempty"`
	OptOutNotificationMethods []string `json:"optOutNotificationMethods,omitempty"`
}

type InitializeParams struct {
	Capabilities *InitializeCapabilities `json:"capabilities,omitempty"`
	ClientInfo   ClientInfo              `json:"clientInfo"`
}

type InitializeResponse struct {
	CodexHome      V2AbsolutePathBuf `json:"codexHome"`
	PlatformFamily string            `json:"platformFamily"`
	PlatformOs     string            `json:"platformOs"`
	UserAgent      string            `json:"userAgent"`
}

type InputModality string

const (
	InputModalityText  InputModality = "text"
	InputModalityImage InputModality = "image"
)

var inputModalityValues = map[string]InputModality{
	"text":  InputModalityText,
	"image": InputModalityImage,
}

func ParseInputModality(value string) (InputModality, bool) {
	return parseStringEnum[InputModality](value, inputModalityValues)
}

func (v InputModality) IsValid() bool {
	return isValidStringEnum(v, inputModalityValues)
}

type ItemCompletedNotification struct {
	Item     ThreadItem `json:"item"`
	ThreadId string     `json:"threadId"`
	TurnId   string     `json:"turnId"`
}

type ItemGuardianApprovalReviewCompletedNotification struct {
	Action       any                    `json:"action,omitempty"`
	Review       GuardianApprovalReview `json:"review"`
	TargetItemId string                 `json:"targetItemId"`
	ThreadId     string                 `json:"threadId"`
	TurnId       string                 `json:"turnId"`
}

type ItemGuardianApprovalReviewStartedNotification struct {
	Action       any                    `json:"action,omitempty"`
	Review       GuardianApprovalReview `json:"review"`
	TargetItemId string                 `json:"targetItemId"`
	ThreadId     string                 `json:"threadId"`
	TurnId       string                 `json:"turnId"`
}

type ItemStartedNotification struct {
	Item     ThreadItem `json:"item"`
	ThreadId string     `json:"threadId"`
	TurnId   string     `json:"turnId"`
}

type McpElicitationArrayType string

const McpElicitationArrayTypeArray McpElicitationArrayType = "array"

var mcpElicitationArrayTypeValues = map[string]McpElicitationArrayType{
	"array": McpElicitationArrayTypeArray,
}

func ParseMcpElicitationArrayType(value string) (McpElicitationArrayType, bool) {
	return parseStringEnum[McpElicitationArrayType](value, mcpElicitationArrayTypeValues)
}

func (v McpElicitationArrayType) IsValid() bool {
	return isValidStringEnum(v, mcpElicitationArrayTypeValues)
}

type McpElicitationBooleanSchema struct {
	Default     *bool                     `json:"default,omitempty"`
	Description *string                   `json:"description,omitempty"`
	Title       *string                   `json:"title,omitempty"`
	Type        McpElicitationBooleanType `json:"type"`
}

type McpElicitationBooleanType string

const McpElicitationBooleanTypeBoolean McpElicitationBooleanType = "boolean"

var mcpElicitationBooleanTypeValues = map[string]McpElicitationBooleanType{
	"boolean": McpElicitationBooleanTypeBoolean,
}

func ParseMcpElicitationBooleanType(value string) (McpElicitationBooleanType, bool) {
	return parseStringEnum[McpElicitationBooleanType](value, mcpElicitationBooleanTypeValues)
}

func (v McpElicitationBooleanType) IsValid() bool {
	return isValidStringEnum(v, mcpElicitationBooleanTypeValues)
}

type McpElicitationConstOption struct {
	Const string `json:"const"`
	Title string `json:"title"`
}

type McpElicitationEnumSchema = json.RawMessage

type McpElicitationLegacyTitledEnumSchema struct {
	Default     *string                  `json:"default,omitempty"`
	Description *string                  `json:"description,omitempty"`
	Enum        []string                 `json:"enum"`
	EnumNames   []string                 `json:"enumNames,omitempty"`
	Title       *string                  `json:"title,omitempty"`
	Type        McpElicitationStringType `json:"type"`
}

type McpElicitationMultiSelectEnumSchema = json.RawMessage

type McpElicitationNumberSchema struct {
	Default     *float64                 `json:"default,omitempty"`
	Description *string                  `json:"description,omitempty"`
	Maximum     *float64                 `json:"maximum,omitempty"`
	Minimum     *float64                 `json:"minimum,omitempty"`
	Title       *string                  `json:"title,omitempty"`
	Type        McpElicitationNumberType `json:"type"`
}

type McpElicitationNumberType string

const (
	McpElicitationNumberTypeNumber  McpElicitationNumberType = "number"
	McpElicitationNumberTypeInteger McpElicitationNumberType = "integer"
)

var mcpElicitationNumberTypeValues = map[string]McpElicitationNumberType{
	"number":  McpElicitationNumberTypeNumber,
	"integer": McpElicitationNumberTypeInteger,
}

func ParseMcpElicitationNumberType(value string) (McpElicitationNumberType, bool) {
	return parseStringEnum[McpElicitationNumberType](value, mcpElicitationNumberTypeValues)
}

func (v McpElicitationNumberType) IsValid() bool {
	return isValidStringEnum(v, mcpElicitationNumberTypeValues)
}

type McpElicitationObjectType string

const McpElicitationObjectTypeObject McpElicitationObjectType = "object"

var mcpElicitationObjectTypeValues = map[string]McpElicitationObjectType{
	"object": McpElicitationObjectTypeObject,
}

func ParseMcpElicitationObjectType(value string) (McpElicitationObjectType, bool) {
	return parseStringEnum[McpElicitationObjectType](value, mcpElicitationObjectTypeValues)
}

func (v McpElicitationObjectType) IsValid() bool {
	return isValidStringEnum(v, mcpElicitationObjectTypeValues)
}

type McpElicitationPrimitiveSchema = json.RawMessage

type McpElicitationSchema struct {
	Schema     *string                                  `json:"$schema,omitempty"`
	Properties map[string]McpElicitationPrimitiveSchema `json:"properties"`
	Required   []string                                 `json:"required,omitempty"`
	Type       McpElicitationObjectType                 `json:"type"`
}

type McpElicitationSingleSelectEnumSchema = json.RawMessage

type McpElicitationStringFormat string

const (
	McpElicitationStringFormatEmail    McpElicitationStringFormat = "email"
	McpElicitationStringFormatURI      McpElicitationStringFormat = "uri"
	McpElicitationStringFormatDate     McpElicitationStringFormat = "date"
	McpElicitationStringFormatDateTime McpElicitationStringFormat = "date-time"
)

var mcpElicitationStringFormatValues = map[string]McpElicitationStringFormat{
	"email":     McpElicitationStringFormatEmail,
	"uri":       McpElicitationStringFormatURI,
	"date":      McpElicitationStringFormatDate,
	"date-time": McpElicitationStringFormatDateTime,
}

func ParseMcpElicitationStringFormat(value string) (McpElicitationStringFormat, bool) {
	return parseStringEnum[McpElicitationStringFormat](value, mcpElicitationStringFormatValues)
}

func (v McpElicitationStringFormat) IsValid() bool {
	return isValidStringEnum(v, mcpElicitationStringFormatValues)
}

type McpElicitationStringSchema struct {
	Default     *string                     `json:"default,omitempty"`
	Description *string                     `json:"description,omitempty"`
	Format      *McpElicitationStringFormat `json:"format,omitempty"`
	MaxLength   *uint32                     `json:"maxLength,omitempty"`
	MinLength   *uint32                     `json:"minLength,omitempty"`
	Title       *string                     `json:"title,omitempty"`
	Type        McpElicitationStringType    `json:"type"`
}

type McpElicitationStringType string

const McpElicitationStringTypeString McpElicitationStringType = "string"

var mcpElicitationStringTypeValues = map[string]McpElicitationStringType{
	"string": McpElicitationStringTypeString,
}

func ParseMcpElicitationStringType(value string) (McpElicitationStringType, bool) {
	return parseStringEnum[McpElicitationStringType](value, mcpElicitationStringTypeValues)
}

func (v McpElicitationStringType) IsValid() bool {
	return isValidStringEnum(v, mcpElicitationStringTypeValues)
}

type McpElicitationTitledEnumItems struct {
	AnyOf []McpElicitationConstOption `json:"anyOf"`
}

type McpElicitationTitledMultiSelectEnumSchema struct {
	Default     []string                      `json:"default,omitempty"`
	Description *string                       `json:"description,omitempty"`
	Items       McpElicitationTitledEnumItems `json:"items"`
	MaxItems    *uint64                       `json:"maxItems,omitempty"`
	MinItems    *uint64                       `json:"minItems,omitempty"`
	Title       *string                       `json:"title,omitempty"`
	Type        McpElicitationArrayType       `json:"type"`
}

type McpElicitationTitledSingleSelectEnumSchema struct {
	Default     *string                     `json:"default,omitempty"`
	Description *string                     `json:"description,omitempty"`
	OneOf       []McpElicitationConstOption `json:"oneOf"`
	Title       *string                     `json:"title,omitempty"`
	Type        McpElicitationStringType    `json:"type"`
}

type McpElicitationUntitledEnumItems struct {
	Enum []string                 `json:"enum"`
	Type McpElicitationStringType `json:"type"`
}

type McpElicitationUntitledMultiSelectEnumSchema struct {
	Default     []string                        `json:"default,omitempty"`
	Description *string                         `json:"description,omitempty"`
	Items       McpElicitationUntitledEnumItems `json:"items"`
	MaxItems    *uint64                         `json:"maxItems,omitempty"`
	MinItems    *uint64                         `json:"minItems,omitempty"`
	Title       *string                         `json:"title,omitempty"`
	Type        McpElicitationArrayType         `json:"type"`
}

type McpElicitationUntitledSingleSelectEnumSchema struct {
	Default     *string                  `json:"default,omitempty"`
	Description *string                  `json:"description,omitempty"`
	Enum        []string                 `json:"enum"`
	Title       *string                  `json:"title,omitempty"`
	Type        McpElicitationStringType `json:"type"`
}

type McpServerElicitationRequestParams struct {
	ServerName string  `json:"serverName"`
	ThreadId   string  `json:"threadId"`
	TurnId     *string `json:"turnId,omitempty"`
}

type McpServerOauthLoginCompletedNotification struct {
	Error   *string `json:"error,omitempty"`
	Name    string  `json:"name"`
	Success bool    `json:"success"`
}

type McpServerStartupState string

const (
	McpServerStartupStateStarting  McpServerStartupState = "starting"
	McpServerStartupStateReady     McpServerStartupState = "ready"
	McpServerStartupStateFailed    McpServerStartupState = "failed"
	McpServerStartupStateCancelled McpServerStartupState = "cancelled"
)

var mcpServerStartupStateValues = map[string]McpServerStartupState{
	"starting":  McpServerStartupStateStarting,
	"ready":     McpServerStartupStateReady,
	"failed":    McpServerStartupStateFailed,
	"cancelled": McpServerStartupStateCancelled,
}

func ParseMcpServerStartupState(value string) (McpServerStartupState, bool) {
	return parseStringEnum[McpServerStartupState](value, mcpServerStartupStateValues)
}

func (v McpServerStartupState) IsValid() bool {
	return isValidStringEnum(v, mcpServerStartupStateValues)
}

type McpServerStatusUpdatedNotification struct {
	Error  *string               `json:"error,omitempty"`
	Name   string                `json:"name"`
	Status McpServerStartupState `json:"status"`
}

type McpToolCallError struct {
	Message string `json:"message"`
}

type McpToolCallProgressNotification struct {
	ItemId   string `json:"itemId"`
	Message  string `json:"message"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type McpToolCallResult struct {
	Content           []any `json:"content"`
	StructuredContent any   `json:"structuredContent,omitempty"`
}

type McpToolCallStatus string

const (
	McpToolCallStatusInProgress McpToolCallStatus = "inProgress"
	McpToolCallStatusCompleted  McpToolCallStatus = "completed"
	McpToolCallStatusFailed     McpToolCallStatus = "failed"
)

var mcpToolCallStatusValues = map[string]McpToolCallStatus{
	"inProgress": McpToolCallStatusInProgress,
	"completed":  McpToolCallStatusCompleted,
	"failed":     McpToolCallStatusFailed,
}

func ParseMcpToolCallStatus(value string) (McpToolCallStatus, bool) {
	return parseStringEnum[McpToolCallStatus](value, mcpToolCallStatusValues)
}

func (v McpToolCallStatus) IsValid() bool {
	return isValidStringEnum(v, mcpToolCallStatusValues)
}

type MemoryCitation struct {
	Entries   []MemoryCitationEntry `json:"entries"`
	ThreadIds []string              `json:"threadIds"`
}

type MemoryCitationEntry struct {
	LineEnd   uint32 `json:"lineEnd"`
	LineStart uint32 `json:"lineStart"`
	Note      string `json:"note"`
	Path      string `json:"path"`
}

type MessagePhase string

const (
	MessagePhaseCommentary  MessagePhase = "commentary"
	MessagePhaseFinalAnswer MessagePhase = "final_answer"
)

var messagePhaseValues = map[string]MessagePhase{
	"commentary":   MessagePhaseCommentary,
	"final_answer": MessagePhaseFinalAnswer,
}

func ParseMessagePhase(value string) (MessagePhase, bool) {
	return parseStringEnum[MessagePhase](value, messagePhaseValues)
}

func (v MessagePhase) IsValid() bool {
	return isValidStringEnum(v, messagePhaseValues)
}

type Model struct {
	AvailabilityNux           *ModelAvailabilityNux   `json:"availabilityNux,omitempty"`
	DefaultReasoningEffort    ReasoningEffort         `json:"defaultReasoningEffort"`
	Description               string                  `json:"description"`
	DisplayName               string                  `json:"displayName"`
	Hidden                    bool                    `json:"hidden"`
	ID                        string                  `json:"id"`
	InputModalities           []InputModality         `json:"inputModalities,omitempty"`
	IsDefault                 bool                    `json:"isDefault"`
	Model                     string                  `json:"model"`
	SupportedReasoningEfforts []ReasoningEffortOption `json:"supportedReasoningEfforts"`
	SupportsPersonality       *bool                   `json:"supportsPersonality,omitempty"`
	Upgrade                   *string                 `json:"upgrade,omitempty"`
	UpgradeInfo               *ModelUpgradeInfo       `json:"upgradeInfo,omitempty"`
}

type ModelAvailabilityNux struct {
	Message string `json:"message"`
}

type ModelListParams struct {
	Cursor        *string `json:"cursor,omitempty"`
	IncludeHidden *bool   `json:"includeHidden,omitempty"`
	Limit         *uint32 `json:"limit,omitempty"`
}

type ModelListResponse struct {
	Data       []Model `json:"data"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

type ModelRerouteReason string

const ModelRerouteReasonHighRiskCyberActivity ModelRerouteReason = "highRiskCyberActivity"

var modelRerouteReasonValues = map[string]ModelRerouteReason{
	"highRiskCyberActivity": ModelRerouteReasonHighRiskCyberActivity,
}

func ParseModelRerouteReason(value string) (ModelRerouteReason, bool) {
	return parseStringEnum[ModelRerouteReason](value, modelRerouteReasonValues)
}

func (v ModelRerouteReason) IsValid() bool {
	return isValidStringEnum(v, modelRerouteReasonValues)
}

type ModelReroutedNotification struct {
	FromModel string             `json:"fromModel"`
	Reason    ModelRerouteReason `json:"reason"`
	ThreadId  string             `json:"threadId"`
	ToModel   string             `json:"toModel"`
	TurnId    string             `json:"turnId"`
}

type ModelUpgradeInfo struct {
	MigrationMarkdown *string `json:"migrationMarkdown,omitempty"`
	Model             string  `json:"model"`
	ModelLink         *string `json:"modelLink,omitempty"`
	UpgradeCopy       *string `json:"upgradeCopy,omitempty"`
}

type NetworkAccess string

const (
	NetworkAccessRestricted NetworkAccess = "restricted"
	NetworkAccessEnabled    NetworkAccess = "enabled"
)

var networkAccessValues = map[string]NetworkAccess{
	"restricted": NetworkAccessRestricted,
	"enabled":    NetworkAccessEnabled,
}

func ParseNetworkAccess(value string) (NetworkAccess, bool) {
	return parseStringEnum[NetworkAccess](value, networkAccessValues)
}

func (v NetworkAccess) IsValid() bool {
	return isValidStringEnum(v, networkAccessValues)
}

type NetworkApprovalContext struct {
	Host     string                  `json:"host"`
	Protocol NetworkApprovalProtocol `json:"protocol"`
}

type NetworkApprovalProtocol string

const (
	NetworkApprovalProtocolHttp      NetworkApprovalProtocol = "http"
	NetworkApprovalProtocolHttps     NetworkApprovalProtocol = "https"
	NetworkApprovalProtocolSocks5Tcp NetworkApprovalProtocol = "socks5Tcp"
	NetworkApprovalProtocolSocks5Udp NetworkApprovalProtocol = "socks5Udp"
)

var networkApprovalProtocolValues = map[string]NetworkApprovalProtocol{
	"http":      NetworkApprovalProtocolHttp,
	"https":     NetworkApprovalProtocolHttps,
	"socks5Tcp": NetworkApprovalProtocolSocks5Tcp,
	"socks5Udp": NetworkApprovalProtocolSocks5Udp,
}

func ParseNetworkApprovalProtocol(value string) (NetworkApprovalProtocol, bool) {
	return parseStringEnum[NetworkApprovalProtocol](value, networkApprovalProtocolValues)
}

func (v NetworkApprovalProtocol) IsValid() bool {
	return isValidStringEnum(v, networkApprovalProtocolValues)
}

type NetworkPolicyAmendment struct {
	Action NetworkPolicyRuleAction `json:"action"`
	Host   string                  `json:"host"`
}

type NetworkPolicyRuleAction string

const (
	NetworkPolicyRuleActionAllow NetworkPolicyRuleAction = "allow"
	NetworkPolicyRuleActionDeny  NetworkPolicyRuleAction = "deny"
)

var networkPolicyRuleActionValues = map[string]NetworkPolicyRuleAction{
	"allow": NetworkPolicyRuleActionAllow,
	"deny":  NetworkPolicyRuleActionDeny,
}

func ParseNetworkPolicyRuleAction(value string) (NetworkPolicyRuleAction, bool) {
	return parseStringEnum[NetworkPolicyRuleAction](value, networkPolicyRuleActionValues)
}

func (v NetworkPolicyRuleAction) IsValid() bool {
	return isValidStringEnum(v, networkPolicyRuleActionValues)
}

type NonSteerableTurnKind string

const (
	NonSteerableTurnKindReview  NonSteerableTurnKind = "review"
	NonSteerableTurnKindCompact NonSteerableTurnKind = "compact"
)

var nonSteerableTurnKindValues = map[string]NonSteerableTurnKind{
	"review":  NonSteerableTurnKindReview,
	"compact": NonSteerableTurnKindCompact,
}

func ParseNonSteerableTurnKind(value string) (NonSteerableTurnKind, bool) {
	return parseStringEnum[NonSteerableTurnKind](value, nonSteerableTurnKindValues)
}

func (v NonSteerableTurnKind) IsValid() bool {
	return isValidStringEnum(v, nonSteerableTurnKindValues)
}

type ParsedCommandType string

const (
	ParsedCommandTypeListFiles ParsedCommandType = "list_files"
	ParsedCommandTypeRead      ParsedCommandType = "read"
	ParsedCommandTypeSearch    ParsedCommandType = "search"
	ParsedCommandTypeUnknown   ParsedCommandType = "unknown"
)

var parsedCommandTypeValues = map[string]ParsedCommandType{
	"list_files": ParsedCommandTypeListFiles,
	"read":       ParsedCommandTypeRead,
	"search":     ParsedCommandTypeSearch,
	"unknown":    ParsedCommandTypeUnknown,
}

func ParseParsedCommandType(value string) (ParsedCommandType, bool) {
	return parseStringEnum[ParsedCommandType](value, parsedCommandTypeValues)
}

func (v ParsedCommandType) IsValid() bool {
	return isValidStringEnum(v, parsedCommandTypeValues)
}

type ParsedCommand struct {
	Type  ParsedCommandType `json:"type"`
	Cmd   string            `json:"cmd"`
	Name  *string           `json:"name,omitempty"`
	Path  *string           `json:"path,omitempty"`
	Query *string           `json:"query,omitempty"`
}

type PatchApplyStatus string

const (
	PatchApplyStatusInProgress PatchApplyStatus = "inProgress"
	PatchApplyStatusCompleted  PatchApplyStatus = "completed"
	PatchApplyStatusFailed     PatchApplyStatus = "failed"
	PatchApplyStatusDeclined   PatchApplyStatus = "declined"
)

var patchApplyStatusValues = map[string]PatchApplyStatus{
	"inProgress": PatchApplyStatusInProgress,
	"completed":  PatchApplyStatusCompleted,
	"failed":     PatchApplyStatusFailed,
	"declined":   PatchApplyStatusDeclined,
}

func ParsePatchApplyStatus(value string) (PatchApplyStatus, bool) {
	return parseStringEnum[PatchApplyStatus](value, patchApplyStatusValues)
}

func (v PatchApplyStatus) IsValid() bool {
	return isValidStringEnum(v, patchApplyStatusValues)
}

type PatchChangeKindType string

const (
	PatchChangeKindTypeAdd    PatchChangeKindType = "add"
	PatchChangeKindTypeDelete PatchChangeKindType = "delete"
	PatchChangeKindTypeUpdate PatchChangeKindType = "update"
)

var patchChangeKindTypeValues = map[string]PatchChangeKindType{
	"add":    PatchChangeKindTypeAdd,
	"delete": PatchChangeKindTypeDelete,
	"update": PatchChangeKindTypeUpdate,
}

func ParsePatchChangeKindType(value string) (PatchChangeKindType, bool) {
	return parseStringEnum[PatchChangeKindType](value, patchChangeKindTypeValues)
}

func (v PatchChangeKindType) IsValid() bool {
	return isValidStringEnum(v, patchChangeKindTypeValues)
}

type PatchChangeKind struct {
	Type     PatchChangeKindType `json:"type"`
	MovePath *string             `json:"move_path,omitempty"`
}

type PermissionsRequestApprovalParams struct {
	ItemId      string                   `json:"itemId"`
	Permissions RequestPermissionProfile `json:"permissions"`
	Reason      *string                  `json:"reason,omitempty"`
	ThreadId    string                   `json:"threadId"`
	TurnId      string                   `json:"turnId"`
}

type Personality string

const (
	PersonalityNone      Personality = "none"
	PersonalityFriendly  Personality = "friendly"
	PersonalityPragmatic Personality = "pragmatic"
)

var personalityValues = map[string]Personality{
	"none":      PersonalityNone,
	"friendly":  PersonalityFriendly,
	"pragmatic": PersonalityPragmatic,
}

func ParsePersonality(value string) (Personality, bool) {
	return parseStringEnum[Personality](value, personalityValues)
}

func (v Personality) IsValid() bool {
	return isValidStringEnum(v, personalityValues)
}

type PlanDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemId   string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type PlanType string

const (
	PlanTypeFree                        PlanType = "free"
	PlanTypeGo                          PlanType = "go"
	PlanTypePlus                        PlanType = "plus"
	PlanTypePro                         PlanType = "pro"
	PlanTypeTeam                        PlanType = "team"
	PlanTypeSelfServeBusinessUsageBased PlanType = "self_serve_business_usage_based"
	PlanTypeBusiness                    PlanType = "business"
	PlanTypeEnterpriseCbpUsageBased     PlanType = "enterprise_cbp_usage_based"
	PlanTypeEnterprise                  PlanType = "enterprise"
	PlanTypeEdu                         PlanType = "edu"
	PlanTypeUnknown                     PlanType = "unknown"
)

var planTypeValues = map[string]PlanType{
	"free":                            PlanTypeFree,
	"go":                              PlanTypeGo,
	"plus":                            PlanTypePlus,
	"pro":                             PlanTypePro,
	"team":                            PlanTypeTeam,
	"self_serve_business_usage_based": PlanTypeSelfServeBusinessUsageBased,
	"business":                        PlanTypeBusiness,
	"enterprise_cbp_usage_based":      PlanTypeEnterpriseCbpUsageBased,
	"enterprise":                      PlanTypeEnterprise,
	"edu":                             PlanTypeEdu,
	"unknown":                         PlanTypeUnknown,
}

func ParsePlanType(value string) (PlanType, bool) {
	return parseStringEnum[PlanType](value, planTypeValues)
}

func (v PlanType) IsValid() bool {
	return isValidStringEnum(v, planTypeValues)
}

type RateLimitSnapshot struct {
	Credits   *CreditsSnapshot `json:"credits,omitempty"`
	LimitId   *string          `json:"limitId,omitempty"`
	LimitName *string          `json:"limitName,omitempty"`
	PlanType  *PlanType        `json:"planType,omitempty"`
	Primary   *RateLimitWindow `json:"primary,omitempty"`
	Secondary *RateLimitWindow `json:"secondary,omitempty"`
}

type RateLimitWindow struct {
	ResetsAt           *int64 `json:"resetsAt,omitempty"`
	UsedPercent        int32  `json:"usedPercent"`
	WindowDurationMins *int64 `json:"windowDurationMins,omitempty"`
}

type ReadOnlyAccessType string

const (
	ReadOnlyAccessTypeFullAccess ReadOnlyAccessType = "fullAccess"
	ReadOnlyAccessTypeRestricted ReadOnlyAccessType = "restricted"
)

var readOnlyAccessTypeValues = map[string]ReadOnlyAccessType{
	"fullAccess": ReadOnlyAccessTypeFullAccess,
	"restricted": ReadOnlyAccessTypeRestricted,
}

func ParseReadOnlyAccessType(value string) (ReadOnlyAccessType, bool) {
	return parseStringEnum[ReadOnlyAccessType](value, readOnlyAccessTypeValues)
}

func (v ReadOnlyAccessType) IsValid() bool {
	return isValidStringEnum(v, readOnlyAccessTypeValues)
}

type ReadOnlyAccess struct {
	Type                    ReadOnlyAccessType `json:"type"`
	IncludePlatformDefaults *bool              `json:"includePlatformDefaults,omitempty"`
	ReadableRoots           []AbsolutePathBuf  `json:"readableRoots,omitempty"`
}

type RealtimeConversationVersion string

const (
	RealtimeConversationVersionV1 RealtimeConversationVersion = "v1"
	RealtimeConversationVersionV2 RealtimeConversationVersion = "v2"
)

var realtimeConversationVersionValues = map[string]RealtimeConversationVersion{
	"v1": RealtimeConversationVersionV1,
	"v2": RealtimeConversationVersionV2,
}

func ParseRealtimeConversationVersion(value string) (RealtimeConversationVersion, bool) {
	return parseStringEnum[RealtimeConversationVersion](value, realtimeConversationVersionValues)
}

func (v RealtimeConversationVersion) IsValid() bool {
	return isValidStringEnum(v, realtimeConversationVersionValues)
}

type ReasoningEffort string

const (
	ReasoningEffortNone    ReasoningEffort = "none"
	ReasoningEffortMinimal ReasoningEffort = "minimal"
	ReasoningEffortLow     ReasoningEffort = "low"
	ReasoningEffortMedium  ReasoningEffort = "medium"
	ReasoningEffortHigh    ReasoningEffort = "high"
	ReasoningEffortXhigh   ReasoningEffort = "xhigh"
)

var reasoningEffortValues = map[string]ReasoningEffort{
	"none":    ReasoningEffortNone,
	"minimal": ReasoningEffortMinimal,
	"low":     ReasoningEffortLow,
	"medium":  ReasoningEffortMedium,
	"high":    ReasoningEffortHigh,
	"xhigh":   ReasoningEffortXhigh,
}

func ParseReasoningEffort(value string) (ReasoningEffort, bool) {
	return parseStringEnum[ReasoningEffort](value, reasoningEffortValues)
}

func (v ReasoningEffort) IsValid() bool {
	return isValidStringEnum(v, reasoningEffortValues)
}

type ReasoningEffortOption struct {
	Description     string          `json:"description"`
	ReasoningEffort ReasoningEffort `json:"reasoningEffort"`
}

type ReasoningSummary = json.RawMessage

type ReasoningSummaryPartAddedNotification struct {
	ItemId       string `json:"itemId"`
	SummaryIndex int64  `json:"summaryIndex"`
	ThreadId     string `json:"threadId"`
	TurnId       string `json:"turnId"`
}

type ReasoningSummaryTextDeltaNotification struct {
	Delta        string `json:"delta"`
	ItemId       string `json:"itemId"`
	SummaryIndex int64  `json:"summaryIndex"`
	ThreadId     string `json:"threadId"`
	TurnId       string `json:"turnId"`
}

type ReasoningTextDeltaNotification struct {
	ContentIndex int64  `json:"contentIndex"`
	Delta        string `json:"delta"`
	ItemId       string `json:"itemId"`
	ThreadId     string `json:"threadId"`
	TurnId       string `json:"turnId"`
}

type RequestId struct {
	String  *string `json:"-"`
	Integer *int64  `json:"-"`
}

func RequestIdFromString(value string) RequestId {
	return RequestId{String: &value}
}

func RequestIdFromInteger(value int64) RequestId {
	return RequestId{Integer: &value}
}

func (v RequestId) MarshalJSON() ([]byte, error) {
	return marshalStringOrInt64Union(v.String, v.Integer)
}

func (v *RequestId) UnmarshalJSON(data []byte) error {
	*v = RequestId{}
	stringValue, integerValue, err := unmarshalStringOrInt64Union(data)
	if err != nil {
		return err
	}
	v.String = stringValue
	v.Integer = integerValue
	return nil
}

type RequestPermissionProfile struct {
	FileSystem *AdditionalFileSystemPermissions `json:"fileSystem,omitempty"`
	Network    *AdditionalNetworkPermissions    `json:"network,omitempty"`
}

type SandboxMode string

const (
	SandboxModeReadOnly         SandboxMode = "read-only"
	SandboxModeWorkspaceWrite   SandboxMode = "workspace-write"
	SandboxModeDangerFullAccess SandboxMode = "danger-full-access"
)

var sandboxModeValues = map[string]SandboxMode{
	"read-only":          SandboxModeReadOnly,
	"workspace-write":    SandboxModeWorkspaceWrite,
	"danger-full-access": SandboxModeDangerFullAccess,
}

func ParseSandboxMode(value string) (SandboxMode, bool) {
	return parseStringEnum[SandboxMode](value, sandboxModeValues)
}

func (v SandboxMode) IsValid() bool {
	return isValidStringEnum(v, sandboxModeValues)
}

type SandboxPolicy = json.RawMessage

type ServerRequestResolvedNotification struct {
	RequestId RequestId `json:"requestId"`
	ThreadId  string    `json:"threadId"`
}

type ServiceTier string

const (
	ServiceTierFast ServiceTier = "fast"
	ServiceTierFlex ServiceTier = "flex"
)

var serviceTierValues = map[string]ServiceTier{
	"fast": ServiceTierFast,
	"flex": ServiceTierFlex,
}

func ParseServiceTier(value string) (ServiceTier, bool) {
	return parseStringEnum[ServiceTier](value, serviceTierValues)
}

func (v ServiceTier) IsValid() bool {
	return isValidStringEnum(v, serviceTierValues)
}

type SessionSourceKind string

const (
	SessionSourceKindAppServer SessionSourceKind = "appServer"
	SessionSourceKindCLI       SessionSourceKind = "cli"
	SessionSourceKindExec      SessionSourceKind = "exec"
	SessionSourceKindUnknown   SessionSourceKind = "unknown"
	SessionSourceKindVscode    SessionSourceKind = "vscode"
)

var sessionSourceKindValues = map[string]SessionSourceKind{
	"appServer": SessionSourceKindAppServer,
	"cli":       SessionSourceKindCLI,
	"exec":      SessionSourceKindExec,
	"unknown":   SessionSourceKindUnknown,
	"vscode":    SessionSourceKindVscode,
}

func ParseSessionSourceKind(value string) (SessionSourceKind, bool) {
	return parseStringEnum[SessionSourceKind](value, sessionSourceKindValues)
}

func (v SessionSourceKind) IsValid() bool {
	return isValidStringEnum(v, sessionSourceKindValues)
}

type SessionSource struct {
	Kind     SessionSourceKind `json:"-"`
	Custom   *string           `json:"-"`
	SubAgent *SubAgentSource   `json:"-"`
}

func (v SessionSource) MarshalJSON() ([]byte, error) {
	return marshalStringOrSingleFieldObjectUnion(v.Kind,
		objectUnionField{name: "custom", value: v.Custom},
		objectUnionField{name: "subAgent", value: v.SubAgent},
	)
}

func (v *SessionSource) UnmarshalJSON(data []byte) error {
	*v = SessionSource{}
	kind, err := unmarshalStringOrSingleFieldObjectUnion[SessionSourceKind](data, sessionSourceKindValues, map[string]func(json.RawMessage) error{
		"custom": func(raw json.RawMessage) error {
			var payload string
			if err := json.Unmarshal(raw, &payload); err != nil {
				return err
			}
			v.Custom = &payload
			return nil
		},
		"subAgent": func(raw json.RawMessage) error {
			var payload SubAgentSource
			if err := json.Unmarshal(raw, &payload); err != nil {
				return err
			}
			v.SubAgent = &payload
			return nil
		},
	})
	if err != nil {
		return err
	}
	v.Kind = kind
	return nil
}

type SkillsChangedNotification map[string]any

type SubAgentSourceThreadSpawn struct {
	AgentNickname  *string    `json:"agent_nickname,omitempty"`
	AgentPath      *AgentPath `json:"agent_path,omitempty"`
	AgentRole      *string    `json:"agent_role,omitempty"`
	Depth          int32      `json:"depth"`
	ParentThreadID ThreadId   `json:"parent_thread_id"`
}

type SubAgentSourceKind string

const (
	SubAgentSourceKindCompact             SubAgentSourceKind = "compact"
	SubAgentSourceKindMemoryConsolidation SubAgentSourceKind = "memory_consolidation"
	SubAgentSourceKindReview              SubAgentSourceKind = "review"
)

var subAgentSourceKindValues = map[string]SubAgentSourceKind{
	"compact":              SubAgentSourceKindCompact,
	"memory_consolidation": SubAgentSourceKindMemoryConsolidation,
	"review":               SubAgentSourceKindReview,
}

func ParseSubAgentSourceKind(value string) (SubAgentSourceKind, bool) {
	return parseStringEnum[SubAgentSourceKind](value, subAgentSourceKindValues)
}

func (v SubAgentSourceKind) IsValid() bool {
	return isValidStringEnum(v, subAgentSourceKindValues)
}

type SubAgentSource struct {
	Kind        SubAgentSourceKind         `json:"-"`
	Other       *string                    `json:"-"`
	ThreadSpawn *SubAgentSourceThreadSpawn `json:"-"`
}

func (v SubAgentSource) MarshalJSON() ([]byte, error) {
	return marshalStringOrSingleFieldObjectUnion(v.Kind,
		objectUnionField{name: "other", value: v.Other},
		objectUnionField{name: "thread_spawn", value: v.ThreadSpawn},
	)
}

func (v *SubAgentSource) UnmarshalJSON(data []byte) error {
	*v = SubAgentSource{}
	kind, err := unmarshalStringOrSingleFieldObjectUnion[SubAgentSourceKind](data, subAgentSourceKindValues, map[string]func(json.RawMessage) error{
		"other": func(raw json.RawMessage) error {
			var payload string
			if err := json.Unmarshal(raw, &payload); err != nil {
				return err
			}
			v.Other = &payload
			return nil
		},
		"thread_spawn": func(raw json.RawMessage) error {
			var payload SubAgentSourceThreadSpawn
			if err := json.Unmarshal(raw, &payload); err != nil {
				return err
			}
			v.ThreadSpawn = &payload
			return nil
		},
	})
	if err != nil {
		return err
	}
	v.Kind = kind
	return nil
}

type TerminalInteractionNotification struct {
	ItemId    string `json:"itemId"`
	ProcessId string `json:"processId"`
	Stdin     string `json:"stdin"`
	ThreadId  string `json:"threadId"`
	TurnId    string `json:"turnId"`
}

type TextElement struct {
	ByteRange   ByteRange `json:"byteRange"`
	Placeholder *string   `json:"placeholder,omitempty"`
}

type TextPosition struct {
	Column uint64 `json:"column"`
	Line   uint64 `json:"line"`
}

type TextRange struct {
	End   TextPosition `json:"end"`
	Start TextPosition `json:"start"`
}

type Thread struct {
	AgentNickname *string       `json:"agentNickname,omitempty"`
	AgentRole     *string       `json:"agentRole,omitempty"`
	CliVersion    string        `json:"cliVersion"`
	CreatedAt     int64         `json:"createdAt"`
	CWD           string        `json:"cwd"`
	Ephemeral     bool          `json:"ephemeral"`
	GitInfo       *GitInfo      `json:"gitInfo,omitempty"`
	ID            string        `json:"id"`
	ModelProvider string        `json:"modelProvider"`
	Name          *string       `json:"name,omitempty"`
	Path          *string       `json:"path,omitempty"`
	Preview       string        `json:"preview"`
	Source        SessionSource `json:"source"`
	Status        ThreadStatus  `json:"status"`
	Turns         []Turn        `json:"turns"`
	UpdatedAt     int64         `json:"updatedAt"`
}

type ThreadActiveFlag string

const (
	ThreadActiveFlagWaitingOnApproval  ThreadActiveFlag = "waitingOnApproval"
	ThreadActiveFlagWaitingOnUserInput ThreadActiveFlag = "waitingOnUserInput"
)

var threadActiveFlagValues = map[string]ThreadActiveFlag{
	"waitingOnApproval":  ThreadActiveFlagWaitingOnApproval,
	"waitingOnUserInput": ThreadActiveFlagWaitingOnUserInput,
}

func ParseThreadActiveFlag(value string) (ThreadActiveFlag, bool) {
	return parseStringEnum[ThreadActiveFlag](value, threadActiveFlagValues)
}

func (v ThreadActiveFlag) IsValid() bool {
	return isValidStringEnum(v, threadActiveFlagValues)
}

type ThreadArchiveParams struct {
	ThreadId string `json:"threadId"`
}

type ThreadArchiveResponse map[string]any

type ThreadArchivedNotification struct {
	ThreadId string `json:"threadId"`
}

type ThreadClosedNotification struct {
	ThreadId string `json:"threadId"`
}

type ThreadCompactStartParams struct {
	ThreadId string `json:"threadId"`
}

type ThreadCompactStartResponse map[string]any

type ThreadForkParams struct {
	ApprovalPolicy        *AskForApproval    `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer     *ApprovalsReviewer `json:"approvalsReviewer,omitempty"`
	BaseInstructions      *string            `json:"baseInstructions,omitempty"`
	Config                map[string]any     `json:"config,omitempty"`
	CWD                   *string            `json:"cwd,omitempty"`
	DeveloperInstructions *string            `json:"developerInstructions,omitempty"`
	Ephemeral             *bool              `json:"ephemeral,omitempty"`
	Model                 *string            `json:"model,omitempty"`
	ModelProvider         *string            `json:"modelProvider,omitempty"`
	Sandbox               *SandboxMode       `json:"sandbox,omitempty"`
	ServiceTier           *ServiceTier       `json:"serviceTier,omitempty"`
	ThreadId              string             `json:"threadId"`
}

type ThreadForkResponse struct {
	ApprovalPolicy    AskForApproval    `json:"approvalPolicy"`
	ApprovalsReviewer ApprovalsReviewer `json:"approvalsReviewer"`
	CWD               string            `json:"cwd"`
	Model             string            `json:"model"`
	ModelProvider     string            `json:"modelProvider"`
	ReasoningEffort   *ReasoningEffort  `json:"reasoningEffort,omitempty"`
	Sandbox           SandboxPolicy     `json:"sandbox"`
	ServiceTier       *ServiceTier      `json:"serviceTier,omitempty"`
	Thread            Thread            `json:"thread"`
}

type ThreadId string

type ThreadItem = json.RawMessage

type ThreadListParams struct {
	Archived       *bool              `json:"archived,omitempty"`
	Cursor         *string            `json:"cursor,omitempty"`
	CWD            *string            `json:"cwd,omitempty"`
	Limit          *uint32            `json:"limit,omitempty"`
	ModelProviders []string           `json:"modelProviders,omitempty"`
	SearchTerm     *string            `json:"searchTerm,omitempty"`
	SortKey        *ThreadSortKey     `json:"sortKey,omitempty"`
	SourceKinds    []ThreadSourceKind `json:"sourceKinds,omitempty"`
}

type ThreadListResponse struct {
	Data       []Thread `json:"data"`
	NextCursor *string  `json:"nextCursor,omitempty"`
}

type ThreadNameUpdatedNotification struct {
	ThreadId   string  `json:"threadId"`
	ThreadName *string `json:"threadName,omitempty"`
}

type ThreadReadParams struct {
	IncludeTurns *bool  `json:"includeTurns,omitempty"`
	ThreadId     string `json:"threadId"`
}

type ThreadReadResponse struct {
	Thread Thread `json:"thread"`
}

type ThreadRealtimeAudioChunk struct {
	Data              string  `json:"data"`
	ItemId            *string `json:"itemId,omitempty"`
	NumChannels       uint16  `json:"numChannels"`
	SampleRate        uint32  `json:"sampleRate"`
	SamplesPerChannel *uint32 `json:"samplesPerChannel,omitempty"`
}

type ThreadRealtimeClosedNotification struct {
	Reason   *string `json:"reason,omitempty"`
	ThreadId string  `json:"threadId"`
}

type ThreadRealtimeErrorNotification struct {
	Message  string `json:"message"`
	ThreadId string `json:"threadId"`
}

type ThreadRealtimeItemAddedNotification struct {
	Item     any    `json:"item"`
	ThreadId string `json:"threadId"`
}

type ThreadRealtimeOutputAudioDeltaNotification struct {
	Audio    ThreadRealtimeAudioChunk `json:"audio"`
	ThreadId string                   `json:"threadId"`
}

type ThreadRealtimeStartedNotification struct {
	SessionId *string                     `json:"sessionId,omitempty"`
	ThreadId  string                      `json:"threadId"`
	Version   RealtimeConversationVersion `json:"version"`
}

type ThreadRealtimeTranscriptUpdatedNotification struct {
	Role     string `json:"role"`
	Text     string `json:"text"`
	ThreadId string `json:"threadId"`
}

type ThreadResumeParams struct {
	ApprovalPolicy        *AskForApproval    `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer     *ApprovalsReviewer `json:"approvalsReviewer,omitempty"`
	BaseInstructions      *string            `json:"baseInstructions,omitempty"`
	Config                map[string]any     `json:"config,omitempty"`
	CWD                   *string            `json:"cwd,omitempty"`
	DeveloperInstructions *string            `json:"developerInstructions,omitempty"`
	Model                 *string            `json:"model,omitempty"`
	ModelProvider         *string            `json:"modelProvider,omitempty"`
	Personality           *Personality       `json:"personality,omitempty"`
	Sandbox               *SandboxMode       `json:"sandbox,omitempty"`
	ServiceTier           *ServiceTier       `json:"serviceTier,omitempty"`
	ThreadId              string             `json:"threadId"`
}

type ThreadResumeResponse struct {
	ApprovalPolicy    AskForApproval    `json:"approvalPolicy"`
	ApprovalsReviewer ApprovalsReviewer `json:"approvalsReviewer"`
	CWD               string            `json:"cwd"`
	Model             string            `json:"model"`
	ModelProvider     string            `json:"modelProvider"`
	ReasoningEffort   *ReasoningEffort  `json:"reasoningEffort,omitempty"`
	Sandbox           SandboxPolicy     `json:"sandbox"`
	ServiceTier       *ServiceTier      `json:"serviceTier,omitempty"`
	Thread            Thread            `json:"thread"`
}

type ThreadSetNameParams struct {
	Name     string `json:"name"`
	ThreadId string `json:"threadId"`
}

type ThreadSetNameResponse map[string]any

type ThreadSortKey string

const (
	ThreadSortKeyCreatedAt ThreadSortKey = "created_at"
	ThreadSortKeyUpdatedAt ThreadSortKey = "updated_at"
)

var threadSortKeyValues = map[string]ThreadSortKey{
	"created_at": ThreadSortKeyCreatedAt,
	"updated_at": ThreadSortKeyUpdatedAt,
}

func ParseThreadSortKey(value string) (ThreadSortKey, bool) {
	return parseStringEnum[ThreadSortKey](value, threadSortKeyValues)
}

func (v ThreadSortKey) IsValid() bool {
	return isValidStringEnum(v, threadSortKeyValues)
}

type ThreadSourceKind string

const (
	ThreadSourceKindCLI                 ThreadSourceKind = "cli"
	ThreadSourceKindVscode              ThreadSourceKind = "vscode"
	ThreadSourceKindExec                ThreadSourceKind = "exec"
	ThreadSourceKindAppServer           ThreadSourceKind = "appServer"
	ThreadSourceKindSubAgent            ThreadSourceKind = "subAgent"
	ThreadSourceKindSubAgentReview      ThreadSourceKind = "subAgentReview"
	ThreadSourceKindSubAgentCompact     ThreadSourceKind = "subAgentCompact"
	ThreadSourceKindSubAgentThreadSpawn ThreadSourceKind = "subAgentThreadSpawn"
	ThreadSourceKindSubAgentOther       ThreadSourceKind = "subAgentOther"
	ThreadSourceKindUnknown             ThreadSourceKind = "unknown"
)

var threadSourceKindValues = map[string]ThreadSourceKind{
	"cli":                 ThreadSourceKindCLI,
	"vscode":              ThreadSourceKindVscode,
	"exec":                ThreadSourceKindExec,
	"appServer":           ThreadSourceKindAppServer,
	"subAgent":            ThreadSourceKindSubAgent,
	"subAgentReview":      ThreadSourceKindSubAgentReview,
	"subAgentCompact":     ThreadSourceKindSubAgentCompact,
	"subAgentThreadSpawn": ThreadSourceKindSubAgentThreadSpawn,
	"subAgentOther":       ThreadSourceKindSubAgentOther,
	"unknown":             ThreadSourceKindUnknown,
}

func ParseThreadSourceKind(value string) (ThreadSourceKind, bool) {
	return parseStringEnum[ThreadSourceKind](value, threadSourceKindValues)
}

func (v ThreadSourceKind) IsValid() bool {
	return isValidStringEnum(v, threadSourceKindValues)
}

type ThreadStartParams struct {
	ApprovalPolicy        *AskForApproval    `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer     *ApprovalsReviewer `json:"approvalsReviewer,omitempty"`
	BaseInstructions      *string            `json:"baseInstructions,omitempty"`
	Config                map[string]any     `json:"config,omitempty"`
	CWD                   *string            `json:"cwd,omitempty"`
	DeveloperInstructions *string            `json:"developerInstructions,omitempty"`
	Ephemeral             *bool              `json:"ephemeral,omitempty"`
	Model                 *string            `json:"model,omitempty"`
	ModelProvider         *string            `json:"modelProvider,omitempty"`
	Personality           *Personality       `json:"personality,omitempty"`
	Sandbox               *SandboxMode       `json:"sandbox,omitempty"`
	ServiceName           *string            `json:"serviceName,omitempty"`
	ServiceTier           *ServiceTier       `json:"serviceTier,omitempty"`
}

type ThreadStartResponse struct {
	ApprovalPolicy    AskForApproval    `json:"approvalPolicy"`
	ApprovalsReviewer ApprovalsReviewer `json:"approvalsReviewer"`
	CWD               string            `json:"cwd"`
	Model             string            `json:"model"`
	ModelProvider     string            `json:"modelProvider"`
	ReasoningEffort   *ReasoningEffort  `json:"reasoningEffort,omitempty"`
	Sandbox           SandboxPolicy     `json:"sandbox"`
	ServiceTier       *ServiceTier      `json:"serviceTier,omitempty"`
	Thread            Thread            `json:"thread"`
}

type ThreadStartedNotification struct {
	Thread Thread `json:"thread"`
}

type ThreadStatusType string

const (
	ThreadStatusTypeActive      ThreadStatusType = "active"
	ThreadStatusTypeIdle        ThreadStatusType = "idle"
	ThreadStatusTypeNotLoaded   ThreadStatusType = "notLoaded"
	ThreadStatusTypeSystemError ThreadStatusType = "systemError"
)

var threadStatusTypeValues = map[string]ThreadStatusType{
	"active":      ThreadStatusTypeActive,
	"idle":        ThreadStatusTypeIdle,
	"notLoaded":   ThreadStatusTypeNotLoaded,
	"systemError": ThreadStatusTypeSystemError,
}

func ParseThreadStatusType(value string) (ThreadStatusType, bool) {
	return parseStringEnum[ThreadStatusType](value, threadStatusTypeValues)
}

func (v ThreadStatusType) IsValid() bool {
	return isValidStringEnum(v, threadStatusTypeValues)
}

type ThreadStatus struct {
	Type        ThreadStatusType   `json:"type"`
	ActiveFlags []ThreadActiveFlag `json:"activeFlags,omitempty"`
}

type ThreadStatusChangedNotification struct {
	Status   ThreadStatus `json:"status"`
	ThreadId string       `json:"threadId"`
}

type ThreadTokenUsage struct {
	Last               TokenUsageBreakdown `json:"last"`
	ModelContextWindow *int64              `json:"modelContextWindow,omitempty"`
	Total              TokenUsageBreakdown `json:"total"`
}

type ThreadTokenUsageUpdatedNotification struct {
	ThreadId   string           `json:"threadId"`
	TokenUsage ThreadTokenUsage `json:"tokenUsage"`
	TurnId     string           `json:"turnId"`
}

type ThreadUnarchiveParams struct {
	ThreadId string `json:"threadId"`
}

type ThreadUnarchiveResponse struct {
	Thread Thread `json:"thread"`
}

type ThreadUnarchivedNotification struct {
	ThreadId string `json:"threadId"`
}

type TokenUsageBreakdown struct {
	CachedInputTokens     int64 `json:"cachedInputTokens"`
	InputTokens           int64 `json:"inputTokens"`
	OutputTokens          int64 `json:"outputTokens"`
	ReasoningOutputTokens int64 `json:"reasoningOutputTokens"`
	TotalTokens           int64 `json:"totalTokens"`
}

type ToolRequestUserInputOption struct {
	Description string `json:"description"`
	Label       string `json:"label"`
}

type ToolRequestUserInputParams struct {
	ItemId    string                         `json:"itemId"`
	Questions []ToolRequestUserInputQuestion `json:"questions"`
	ThreadId  string                         `json:"threadId"`
	TurnId    string                         `json:"turnId"`
}

type ToolRequestUserInputQuestion struct {
	Header   string                       `json:"header"`
	ID       string                       `json:"id"`
	IsOther  *bool                        `json:"isOther,omitempty"`
	IsSecret *bool                        `json:"isSecret,omitempty"`
	Options  []ToolRequestUserInputOption `json:"options,omitempty"`
	Question string                       `json:"question"`
}

type Turn struct {
	Error  *TurnError   `json:"error,omitempty"`
	ID     string       `json:"id"`
	Items  []ThreadItem `json:"items"`
	Status TurnStatus   `json:"status"`
}

type TurnCompletedNotification struct {
	ThreadId string `json:"threadId"`
	Turn     Turn   `json:"turn"`
}

type TurnDiffUpdatedNotification struct {
	Diff     string `json:"diff"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type TurnError struct {
	AdditionalDetails *string         `json:"additionalDetails,omitempty"`
	CodexErrorInfo    *CodexErrorInfo `json:"codexErrorInfo,omitempty"`
	Message           string          `json:"message"`
}

type TurnInterruptParams struct {
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type TurnInterruptResponse map[string]any

type TurnPlanStep struct {
	Status TurnPlanStepStatus `json:"status"`
	Step   string             `json:"step"`
}

type TurnPlanStepStatus string

const (
	TurnPlanStepStatusPending    TurnPlanStepStatus = "pending"
	TurnPlanStepStatusInProgress TurnPlanStepStatus = "inProgress"
	TurnPlanStepStatusCompleted  TurnPlanStepStatus = "completed"
)

var turnPlanStepStatusValues = map[string]TurnPlanStepStatus{
	"pending":    TurnPlanStepStatusPending,
	"inProgress": TurnPlanStepStatusInProgress,
	"completed":  TurnPlanStepStatusCompleted,
}

func ParseTurnPlanStepStatus(value string) (TurnPlanStepStatus, bool) {
	return parseStringEnum[TurnPlanStepStatus](value, turnPlanStepStatusValues)
}

func (v TurnPlanStepStatus) IsValid() bool {
	return isValidStringEnum(v, turnPlanStepStatusValues)
}

type TurnPlanUpdatedNotification struct {
	Explanation *string        `json:"explanation,omitempty"`
	Plan        []TurnPlanStep `json:"plan"`
	ThreadId    string         `json:"threadId"`
	TurnId      string         `json:"turnId"`
}

type TurnStartParams struct {
	ApprovalPolicy    *AskForApproval    `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer *ApprovalsReviewer `json:"approvalsReviewer,omitempty"`
	CWD               *string            `json:"cwd,omitempty"`
	Effort            *ReasoningEffort   `json:"effort,omitempty"`
	Input             []UserInput        `json:"input"`
	Model             *string            `json:"model,omitempty"`
	OutputSchema      json.RawMessage    `json:"outputSchema,omitempty"`
	Personality       *Personality       `json:"personality,omitempty"`
	SandboxPolicy     *SandboxPolicy     `json:"sandboxPolicy,omitempty"`
	ServiceTier       *ServiceTier       `json:"serviceTier,omitempty"`
	Summary           *ReasoningSummary  `json:"summary,omitempty"`
	ThreadId          string             `json:"threadId"`
}

type TurnStartResponse struct {
	Turn Turn `json:"turn"`
}

type TurnStartedNotification struct {
	ThreadId string `json:"threadId"`
	Turn     Turn   `json:"turn"`
}

type TurnStatus string

const (
	TurnStatusCompleted   TurnStatus = "completed"
	TurnStatusInterrupted TurnStatus = "interrupted"
	TurnStatusFailed      TurnStatus = "failed"
	TurnStatusInProgress  TurnStatus = "inProgress"
)

var turnStatusValues = map[string]TurnStatus{
	"completed":   TurnStatusCompleted,
	"interrupted": TurnStatusInterrupted,
	"failed":      TurnStatusFailed,
	"inProgress":  TurnStatusInProgress,
}

func ParseTurnStatus(value string) (TurnStatus, bool) {
	return parseStringEnum[TurnStatus](value, turnStatusValues)
}

func (v TurnStatus) IsValid() bool {
	return isValidStringEnum(v, turnStatusValues)
}

type TurnSteerParams struct {
	ExpectedTurnId string      `json:"expectedTurnId"`
	Input          []UserInput `json:"input"`
	ThreadId       string      `json:"threadId"`
}

type TurnSteerResponse struct {
	TurnId string `json:"turnId"`
}

type UserInputType string

const (
	UserInputTypeImage      UserInputType = "image"
	UserInputTypeLocalImage UserInputType = "localImage"
	UserInputTypeMention    UserInputType = "mention"
	UserInputTypeSkill      UserInputType = "skill"
	UserInputTypeText       UserInputType = "text"
)

var userInputTypeValues = map[string]UserInputType{
	"image":      UserInputTypeImage,
	"localImage": UserInputTypeLocalImage,
	"mention":    UserInputTypeMention,
	"skill":      UserInputTypeSkill,
	"text":       UserInputTypeText,
}

func ParseUserInputType(value string) (UserInputType, bool) {
	return parseStringEnum[UserInputType](value, userInputTypeValues)
}

func (v UserInputType) IsValid() bool {
	return isValidStringEnum(v, userInputTypeValues)
}

type UserInput struct {
	Type         UserInputType `json:"type"`
	Name         *string       `json:"name,omitempty"`
	Path         *string       `json:"path,omitempty"`
	Text         *string       `json:"text,omitempty"`
	TextElements []TextElement `json:"text_elements,omitempty"`
	URL          *string       `json:"url,omitempty"`
}

type WebSearchActionType string

const (
	WebSearchActionTypeFindInPage WebSearchActionType = "findInPage"
	WebSearchActionTypeOpenPage   WebSearchActionType = "openPage"
	WebSearchActionTypeOther      WebSearchActionType = "other"
	WebSearchActionTypeSearch     WebSearchActionType = "search"
)

var webSearchActionTypeValues = map[string]WebSearchActionType{
	"findInPage": WebSearchActionTypeFindInPage,
	"openPage":   WebSearchActionTypeOpenPage,
	"other":      WebSearchActionTypeOther,
	"search":     WebSearchActionTypeSearch,
}

func ParseWebSearchActionType(value string) (WebSearchActionType, bool) {
	return parseStringEnum[WebSearchActionType](value, webSearchActionTypeValues)
}

func (v WebSearchActionType) IsValid() bool {
	return isValidStringEnum(v, webSearchActionTypeValues)
}

type WebSearchAction struct {
	Type    WebSearchActionType `json:"type"`
	Pattern *string             `json:"pattern,omitempty"`
	Queries []string            `json:"queries,omitempty"`
	Query   *string             `json:"query,omitempty"`
	URL     *string             `json:"url,omitempty"`
}

type WindowsSandboxSetupCompletedNotification struct {
	Error   *string                 `json:"error,omitempty"`
	Mode    WindowsSandboxSetupMode `json:"mode"`
	Success bool                    `json:"success"`
}

type WindowsSandboxSetupMode string

const (
	WindowsSandboxSetupModeElevated   WindowsSandboxSetupMode = "elevated"
	WindowsSandboxSetupModeUnelevated WindowsSandboxSetupMode = "unelevated"
)

var windowsSandboxSetupModeValues = map[string]WindowsSandboxSetupMode{
	"elevated":   WindowsSandboxSetupModeElevated,
	"unelevated": WindowsSandboxSetupModeUnelevated,
}

func ParseWindowsSandboxSetupMode(value string) (WindowsSandboxSetupMode, bool) {
	return parseStringEnum[WindowsSandboxSetupMode](value, windowsSandboxSetupModeValues)
}

func (v WindowsSandboxSetupMode) IsValid() bool {
	return isValidStringEnum(v, windowsSandboxSetupModeValues)
}

type WindowsWorldWritableWarningNotification struct {
	ExtraCount  uint64   `json:"extraCount"`
	FailedScan  bool     `json:"failedScan"`
	SamplePaths []string `json:"samplePaths"`
}

type V2AbsolutePathBuf any

type V2CommandAction any

type V2ThreadId any
