// Code generated by cmd/updatesdkartifacts; DO NOT EDIT.

package protocol

// NotificationFactory returns a pointer to a notification payload type.
type NotificationFactory = func() any

// ServerRequestFactory returns a pointer to a server-request payload type.
type ServerRequestFactory = func() any

var NotificationFactories = map[string]NotificationFactory{
	"account/login/completed": func() any {
		return &AccountLoginCompletedNotification{}
	},
	"account/rateLimits/updated": func() any {
		return &AccountRateLimitsUpdatedNotification{}
	},
	"account/updated": func() any {
		return &AccountUpdatedNotification{}
	},
	"app/list/updated": func() any {
		return &AppListUpdatedNotification{}
	},
	"command/exec/outputDelta": func() any {
		return &CommandExecOutputDeltaNotification{}
	},
	"configWarning": func() any {
		return &ConfigWarningNotification{}
	},
	"deprecationNotice": func() any {
		return &DeprecationNoticeNotification{}
	},
	"error": func() any {
		return &ErrorNotification{}
	},
	"fs/changed": func() any {
		return &FsChangedNotification{}
	},
	"fuzzyFileSearch/sessionCompleted": func() any {
		return &FuzzyFileSearchSessionCompletedNotification{}
	},
	"fuzzyFileSearch/sessionUpdated": func() any {
		return &FuzzyFileSearchSessionUpdatedNotification{}
	},
	"hook/completed": func() any {
		return &HookCompletedNotification{}
	},
	"hook/started": func() any {
		return &HookStartedNotification{}
	},
	"item/agentMessage/delta": func() any {
		return &AgentMessageDeltaNotification{}
	},
	"item/autoApprovalReview/completed": func() any {
		return &ItemGuardianApprovalReviewCompletedNotification{}
	},
	"item/autoApprovalReview/started": func() any {
		return &ItemGuardianApprovalReviewStartedNotification{}
	},
	"item/commandExecution/outputDelta": func() any {
		return &CommandExecutionOutputDeltaNotification{}
	},
	"item/commandExecution/terminalInteraction": func() any {
		return &TerminalInteractionNotification{}
	},
	"item/completed": func() any {
		return &ItemCompletedNotification{}
	},
	"item/fileChange/outputDelta": func() any {
		return &FileChangeOutputDeltaNotification{}
	},
	"item/mcpToolCall/progress": func() any {
		return &McpToolCallProgressNotification{}
	},
	"item/plan/delta": func() any {
		return &PlanDeltaNotification{}
	},
	"item/reasoning/summaryPartAdded": func() any {
		return &ReasoningSummaryPartAddedNotification{}
	},
	"item/reasoning/summaryTextDelta": func() any {
		return &ReasoningSummaryTextDeltaNotification{}
	},
	"item/reasoning/textDelta": func() any {
		return &ReasoningTextDeltaNotification{}
	},
	"item/started": func() any {
		return &ItemStartedNotification{}
	},
	"mcpServer/oauthLogin/completed": func() any {
		return &McpServerOauthLoginCompletedNotification{}
	},
	"mcpServer/startupStatus/updated": func() any {
		return &McpServerStatusUpdatedNotification{}
	},
	"model/rerouted": func() any {
		return &ModelReroutedNotification{}
	},
	"serverRequest/resolved": func() any {
		return &ServerRequestResolvedNotification{}
	},
	"skills/changed": func() any {
		return &SkillsChangedNotification{}
	},
	"thread/archived": func() any {
		return &ThreadArchivedNotification{}
	},
	"thread/closed": func() any {
		return &ThreadClosedNotification{}
	},
	"thread/compacted": func() any {
		return &ContextCompactedNotification{}
	},
	"thread/name/updated": func() any {
		return &ThreadNameUpdatedNotification{}
	},
	"thread/realtime/closed": func() any {
		return &ThreadRealtimeClosedNotification{}
	},
	"thread/realtime/error": func() any {
		return &ThreadRealtimeErrorNotification{}
	},
	"thread/realtime/itemAdded": func() any {
		return &ThreadRealtimeItemAddedNotification{}
	},
	"thread/realtime/outputAudio/delta": func() any {
		return &ThreadRealtimeOutputAudioDeltaNotification{}
	},
	"thread/realtime/started": func() any {
		return &ThreadRealtimeStartedNotification{}
	},
	"thread/realtime/transcriptUpdated": func() any {
		return &ThreadRealtimeTranscriptUpdatedNotification{}
	},
	"thread/started": func() any {
		return &ThreadStartedNotification{}
	},
	"thread/status/changed": func() any {
		return &ThreadStatusChangedNotification{}
	},
	"thread/tokenUsage/updated": func() any {
		return &ThreadTokenUsageUpdatedNotification{}
	},
	"thread/unarchived": func() any {
		return &ThreadUnarchivedNotification{}
	},
	"turn/completed": func() any {
		return &TurnCompletedNotification{}
	},
	"turn/diff/updated": func() any {
		return &TurnDiffUpdatedNotification{}
	},
	"turn/plan/updated": func() any {
		return &TurnPlanUpdatedNotification{}
	},
	"turn/started": func() any {
		return &TurnStartedNotification{}
	},
	"windows/worldWritableWarning": func() any {
		return &WindowsWorldWritableWarningNotification{}
	},
	"windowsSandbox/setupCompleted": func() any {
		return &WindowsSandboxSetupCompletedNotification{}
	},
}

var ServerRequestFactories = map[string]ServerRequestFactory{
	"account/chatgptAuthTokens/refresh": func() any {
		return &ChatgptAuthTokensRefreshParams{}
	},
	"applyPatchApproval": func() any {
		return &ApplyPatchApprovalParams{}
	},
	"execCommandApproval": func() any {
		return &ExecCommandApprovalParams{}
	},
	"item/commandExecution/requestApproval": func() any {
		return &CommandExecutionRequestApprovalParams{}
	},
	"item/fileChange/requestApproval": func() any {
		return &FileChangeRequestApprovalParams{}
	},
	"item/permissions/requestApproval": func() any {
		return &PermissionsRequestApprovalParams{}
	},
	"item/tool/call": func() any {
		return &DynamicToolCallParams{}
	},
	"item/tool/requestUserInput": func() any {
		return &ToolRequestUserInputParams{}
	},
	"mcpServer/elicitation/request": func() any {
		return &McpServerElicitationRequestParams{}
	},
}
