package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"
)

const (
	defaultSchemaRepo           = "openai/codex"
	defaultSchemaRef            = "main"
	defaultSchemaPath           = "codex-rs/app-server-protocol/schema/json"
	defaultSchemaTimeoutSeconds = 30.0
	generatorHeader             = "// Code generated by cmd/updatesdkartifacts; DO NOT EDIT.\n\n"
	generatorUserAgent          = "codex-go-sdk-schema-generator/0.1"
)

var (
	initialisms = map[string]string{
		"api":     "API",
		"cli":     "CLI",
		"cwd":     "CWD",
		"id":      "ID",
		"json":    "JSON",
		"jsonrpc": "JSONRPC",
		"mcp":     "MCP",
		"rpc":     "RPC",
		"sse":     "SSE",
		"ts":      "TS",
		"ttl":     "TTL",
		"ui":      "UI",
		"uri":     "URI",
		"url":     "URL",
		"uuid":    "UUID",
	}
	coreDefinitions = map[string]struct{}{
		"InitializeParams":           {},
		"InitializeResponse":         {},
		"ModelListParams":            {},
		"ModelListResponse":          {},
		"ThreadArchiveParams":        {},
		"ThreadArchiveResponse":      {},
		"ThreadCompactStartParams":   {},
		"ThreadCompactStartResponse": {},
		"ThreadForkParams":           {},
		"ThreadForkResponse":         {},
		"ThreadListParams":           {},
		"ThreadListResponse":         {},
		"ThreadReadParams":           {},
		"ThreadReadResponse":         {},
		"ThreadResumeParams":         {},
		"ThreadResumeResponse":       {},
		"ThreadSetNameParams":        {},
		"ThreadSetNameResponse":      {},
		"ThreadStartParams":          {},
		"ThreadStartResponse":        {},
		"ThreadUnarchiveParams":      {},
		"ThreadUnarchiveResponse":    {},
		"TurnInterruptParams":        {},
		"TurnInterruptResponse":      {},
		"TurnStartParams":            {},
		"TurnStartResponse":          {},
		"TurnSteerParams":            {},
		"TurnSteerResponse":          {},
	}
	nonAlphaNumeric = regexp.MustCompile(`[^0-9A-Za-z]+`)
)

type generator struct {
	protocolDir     string
	schemaRoot      string
	schemaBaseURL   string
	schemaClient    *http.Client
	cachedDocuments map[string]*schemaNode
}

type methodSpec struct {
	Method   string
	TypeName string
}

type schemaNode struct {
	Ref                  string                 `json:"$ref,omitempty"`
	Type                 schemaType             `json:"type,omitempty"`
	Format               string                 `json:"format,omitempty"`
	Enum                 schemaEnum             `json:"enum,omitempty"`
	AllOf                []schemaValue          `json:"allOf,omitempty"`
	OneOf                []schemaValue          `json:"oneOf,omitempty"`
	AnyOf                []schemaValue          `json:"anyOf,omitempty"`
	Properties           map[string]schemaValue `json:"properties,omitempty"`
	Required             []string               `json:"required,omitempty"`
	AdditionalProperties *schemaValue           `json:"additionalProperties,omitempty"`
	Items                *schemaValue           `json:"items,omitempty"`
	Definitions          map[string]*schemaNode `json:"definitions,omitempty"`
	Description          string                 `json:"description,omitempty"`
	Title                string                 `json:"title,omitempty"`
}

type schemaType struct {
	Values []string
}

type schemaValue struct {
	Bool *bool
	Node *schemaNode
}

type schemaEnum struct {
	Values []schemaEnumValue
}

type schemaEnumValueKind int

const (
	schemaEnumValueUnknown schemaEnumValueKind = iota
	schemaEnumValueString
	schemaEnumValueInteger
)

type schemaEnumValue struct {
	Kind         schemaEnumValueKind
	StringValue  string
	IntegerValue int64
	RawValue     string
}

type goRenderer struct {
	needsJSONImport bool
}

func main() {
	if len(os.Args) != 2 {
		exitf("usage: %s generate-types", filepath.Base(os.Args[0]))
	}

	repoRoot, err := findRepoRoot()
	if err != nil {
		exitErr(err)
	}

	gen, err := newGenerator(repoRoot)
	if err != nil {
		exitErr(err)
	}

	switch os.Args[1] {
	case "generate-types":
		if err := gen.writeGeneratedFiles(); err != nil {
			exitErr(err)
		}
	default:
		exitf("unknown command %q", os.Args[1])
	}
}

func exitf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

func exitErr(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repo root from %s", dir)
		}
		dir = parent
	}
}

func newGenerator(repoRoot string) (*generator, error) {
	schemaRoot := ""
	if override := os.Getenv("CODEX_GO_SCHEMA_ROOT"); override != "" {
		absRoot, err := filepath.Abs(override)
		if err != nil {
			return nil, err
		}
		schemaRoot = absRoot
	}

	timeout, err := schemaFetchTimeout()
	if err != nil {
		return nil, err
	}

	return &generator{
		protocolDir:   filepath.Join(repoRoot, "codex", "protocol"),
		schemaRoot:    schemaRoot,
		schemaBaseURL: schemaBaseURL(),
		schemaClient: &http.Client{
			Timeout: timeout,
		},
		cachedDocuments: make(map[string]*schemaNode),
	}, nil
}

func schemaBaseURL() string {
	if override := os.Getenv("CODEX_GO_SCHEMA_BASE_URL"); override != "" {
		return strings.TrimRight(override, "/")
	}

	repo := strings.Trim(os.Getenv("CODEX_GO_SCHEMA_REPO"), "/")
	if repo == "" {
		repo = defaultSchemaRepo
	}

	ref := os.Getenv("CODEX_GO_SCHEMA_REF")
	if ref == "" {
		ref = defaultSchemaRef
	}

	return fmt.Sprintf("https://raw.githubusercontent.com/%s/%s/%s", repo, ref, defaultSchemaPath)
}

func schemaFetchTimeout() (time.Duration, error) {
	raw := os.Getenv("CODEX_GO_SCHEMA_TIMEOUT")
	if raw == "" {
		return time.Duration(defaultSchemaTimeoutSeconds * float64(time.Second)), nil
	}

	seconds, err := strconv.ParseFloat(raw, 64)
	if err != nil {
		return 0, fmt.Errorf("CODEX_GO_SCHEMA_TIMEOUT must be numeric, got %q", raw)
	}
	if seconds <= 0 {
		return 0, fmt.Errorf("CODEX_GO_SCHEMA_TIMEOUT must be > 0, got %q", raw)
	}
	return time.Duration(seconds * float64(time.Second)), nil
}

func (t *schemaType) UnmarshalJSON(data []byte) error {
	trimmed := bytes.TrimSpace(data)
	if len(trimmed) == 0 || bytes.Equal(trimmed, []byte("null")) {
		t.Values = nil
		return nil
	}

	var single string
	if err := json.Unmarshal(trimmed, &single); err == nil {
		t.Values = []string{single}
		return nil
	}

	var multi []string
	if err := json.Unmarshal(trimmed, &multi); err == nil {
		t.Values = multi
		return nil
	}

	return fmt.Errorf("unsupported schema type: %s", trimmed)
}

func (t schemaType) IsSingle(value string) bool {
	return len(t.Values) == 1 && t.Values[0] == value
}

func (t schemaType) NonNullSingleNullable() (string, bool) {
	if len(t.Values) <= 1 {
		return "", false
	}

	var nonNull string
	nonNullCount := 0
	nullCount := 0
	for _, value := range t.Values {
		if value == "null" {
			nullCount++
			continue
		}
		nonNull = value
		nonNullCount++
	}

	if nonNullCount == 1 && nullCount > 0 {
		return nonNull, true
	}
	return "", false
}

func (v *schemaValue) UnmarshalJSON(data []byte) error {
	trimmed := bytes.TrimSpace(data)
	if len(trimmed) == 0 {
		return nil
	}

	var boolValue bool
	if err := json.Unmarshal(trimmed, &boolValue); err == nil {
		v.Bool = &boolValue
		v.Node = nil
		return nil
	}

	var node schemaNode
	if err := json.Unmarshal(trimmed, &node); err != nil {
		return err
	}
	v.Bool = nil
	v.Node = &node
	return nil
}

func (v schemaValue) NodeOrNil() *schemaNode {
	return v.Node
}

func (e *schemaEnum) UnmarshalJSON(data []byte) error {
	trimmed := bytes.TrimSpace(data)
	if len(trimmed) == 0 || bytes.Equal(trimmed, []byte("null")) {
		e.Values = nil
		return nil
	}

	var rawValues []json.RawMessage
	if err := json.Unmarshal(trimmed, &rawValues); err != nil {
		return err
	}

	values := make([]schemaEnumValue, 0, len(rawValues))
	for _, raw := range rawValues {
		var stringValue string
		if err := json.Unmarshal(raw, &stringValue); err == nil {
			values = append(values, schemaEnumValue{
				Kind:        schemaEnumValueString,
				StringValue: stringValue,
			})
			continue
		}

		var intValue int64
		if err := json.Unmarshal(raw, &intValue); err == nil {
			values = append(values, schemaEnumValue{
				Kind:         schemaEnumValueInteger,
				IntegerValue: intValue,
			})
			continue
		}

		values = append(values, schemaEnumValue{
			Kind:     schemaEnumValueUnknown,
			RawValue: string(raw),
		})
	}

	e.Values = values
	return nil
}

func (e schemaEnum) Strings() ([]string, bool) {
	if len(e.Values) == 0 {
		return nil, false
	}

	out := make([]string, 0, len(e.Values))
	for _, value := range e.Values {
		if value.Kind != schemaEnumValueString {
			return nil, false
		}
		out = append(out, value.StringValue)
	}
	return out, true
}

func (e schemaEnum) Integers() ([]int64, bool) {
	if len(e.Values) == 0 {
		return nil, false
	}

	out := make([]int64, 0, len(e.Values))
	for _, value := range e.Values {
		if value.Kind != schemaEnumValueInteger {
			return nil, false
		}
		out = append(out, value.IntegerValue)
	}
	return out, true
}

func (n *schemaNode) isStringEnumBranch() (string, bool) {
	if n == nil || !n.Type.IsSingle("string") {
		return "", false
	}

	values, ok := n.Enum.Strings()
	if !ok || len(values) != 1 {
		return "", false
	}

	if n.Ref != "" ||
		n.Format != "" ||
		len(n.AllOf) != 0 ||
		len(n.OneOf) != 0 ||
		len(n.AnyOf) != 0 ||
		len(n.Properties) != 0 ||
		len(n.Required) != 0 ||
		n.AdditionalProperties != nil ||
		n.Items != nil ||
		len(n.Definitions) != 0 {
		return "", false
	}

	return values[0], true
}

func cloneNode(source *schemaNode) *schemaNode {
	if source == nil {
		return nil
	}
	cloned := *source
	return &cloned
}

func (g *generator) loadJSON(name string) (*schemaNode, error) {
	if cached, ok := g.cachedDocuments[name]; ok {
		return cached, nil
	}

	var (
		raw    []byte
		source string
		err    error
	)

	if g.schemaRoot != "" {
		source = filepath.Join(g.schemaRoot, name)
		raw, err = os.ReadFile(source)
		if err != nil {
			return nil, err
		}
	} else {
		source = g.schemaBaseURL + "/" + name
		request, err := http.NewRequest(http.MethodGet, source, nil)
		if err != nil {
			return nil, err
		}
		request.Header.Set("User-Agent", generatorUserAgent)

		response, err := g.schemaClient.Do(request)
		if err != nil {
			return nil, fmt.Errorf("schema fetch failed for %s: %w", source, err)
		}
		defer response.Body.Close()

		raw, err = io.ReadAll(response.Body)
		if err != nil {
			return nil, fmt.Errorf("schema fetch failed for %s: %w", source, err)
		}
		if response.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("schema fetch failed for %s: unexpected status %s", source, response.Status)
		}
	}

	var document schemaNode
	if err := json.Unmarshal(raw, &document); err != nil {
		return nil, err
	}

	g.cachedDocuments[name] = &document
	return &document, nil
}

func (g *generator) writeGeneratedFiles() error {
	if err := os.MkdirAll(g.protocolDir, 0o755); err != nil {
		return err
	}

	typesSource, err := g.renderGeneratedTypesSource()
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(g.protocolDir, "generated.go"), []byte(typesSource), 0o644); err != nil {
		return err
	}

	registrySource, err := g.renderGeneratedRegistrySource()
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(g.protocolDir, "registry_generated.go"), []byte(registrySource), 0o644)
}

func (g *generator) renderGeneratedTypesSource() (string, error) {
	definitions, err := g.mergeDefinitions()
	if err != nil {
		return "", err
	}

	selected, err := g.collectDefinitionClosure(definitions)
	if err != nil {
		return "", err
	}

	renderer := &goRenderer{}
	blocks := make([]string, 0, len(selected)+1)
	for _, name := range selected {
		for _, decl := range renderer.topLevelDecl(name, definitions[name]) {
			block, err := formatDecl(decl)
			if err != nil {
				return "", err
			}
			blocks = append(blocks, block)
		}
	}

	if renderer.needsJSONImport {
		importBlock, err := formatDecl(importDecl("encoding/json"))
		if err != nil {
			return "", err
		}
		blocks = append([]string{importBlock}, blocks...)
	}

	return formatSourceBlocks(blocks)
}

func (g *generator) renderGeneratedRegistrySource() (string, error) {
	notifications, err := g.notificationSpecs()
	if err != nil {
		return "", err
	}
	serverRequests, err := g.serverRequestSpecs()
	if err != nil {
		return "", err
	}

	blocks := make([]string, 0, 4)
	for _, item := range []struct {
		comment string
		decl    ast.Decl
	}{
		{
			comment: "NotificationFactory returns a pointer to a notification payload type.",
			decl: typeAliasDecl(
				"NotificationFactory",
				funcTypeNoArgs(anyIdent()),
			),
		},
		{
			comment: "ServerRequestFactory returns a pointer to a server-request payload type.",
			decl: typeAliasDecl(
				"ServerRequestFactory",
				funcTypeNoArgs(anyIdent()),
			),
		},
	} {
		block, err := formatDecl(item.decl)
		if err != nil {
			return "", err
		}
		blocks = append(blocks, "// "+item.comment+"\n"+block)
	}

	notificationMap, err := renderMethodFactoryMapSource("NotificationFactories", "NotificationFactory", notifications)
	if err != nil {
		return "", err
	}
	serverRequestMap, err := renderMethodFactoryMapSource("ServerRequestFactories", "ServerRequestFactory", serverRequests)
	if err != nil {
		return "", err
	}
	blocks = append(blocks, notificationMap, serverRequestMap)

	return formatSourceBlocks(blocks)
}

func (g *generator) mergeDefinitions() (map[string]*schemaNode, error) {
	rootBundle, err := g.loadJSON("codex_app_server_protocol.schemas.json")
	if err != nil {
		return nil, err
	}
	v2Bundle, err := g.loadJSON("codex_app_server_protocol.v2.schemas.json")
	if err != nil {
		return nil, err
	}

	if rootBundle.Definitions == nil || v2Bundle.Definitions == nil {
		return nil, fmt.Errorf("schema bundle is missing definitions")
	}

	merged := make(map[string]*schemaNode, len(rootBundle.Definitions)+len(v2Bundle.Definitions))
	for name, definition := range rootBundle.Definitions {
		merged[name] = definition
	}
	for name, definition := range v2Bundle.Definitions {
		merged[name] = definition
	}
	return merged, nil
}

func (g *generator) notificationSpecs() ([]methodSpec, error) {
	schema, err := g.loadJSON("ServerNotification.json")
	if err != nil {
		return nil, err
	}
	return messageSpecs(schema), nil
}

func (g *generator) serverRequestSpecs() ([]methodSpec, error) {
	schema, err := g.loadJSON("ServerRequest.json")
	if err != nil {
		return nil, err
	}
	return messageSpecs(schema), nil
}

func messageSpecs(schema *schemaNode) []methodSpec {
	if schema == nil {
		return nil
	}

	out := make([]methodSpec, 0, len(schema.OneOf))
	for _, variant := range schema.OneOf {
		variantNode := variant.NodeOrNil()
		if variantNode == nil {
			continue
		}

		methodMetaValue, ok := variantNode.Properties["method"]
		if !ok {
			continue
		}
		paramsMetaValue, ok := variantNode.Properties["params"]
		if !ok {
			continue
		}

		methodMeta := methodMetaValue.NodeOrNil()
		paramsMeta := paramsMetaValue.NodeOrNil()
		if methodMeta == nil || paramsMeta == nil {
			continue
		}

		methods, ok := methodMeta.Enum.Strings()
		if !ok || len(methods) != 1 {
			continue
		}
		if !strings.HasPrefix(paramsMeta.Ref, "#/definitions/") {
			continue
		}

		out = append(out, methodSpec{
			Method:   methods[0],
			TypeName: strings.TrimPrefix(paramsMeta.Ref, "#/definitions/"),
		})
	}

	sort.Slice(out, func(i, j int) bool {
		if out[i].Method == out[j].Method {
			return out[i].TypeName < out[j].TypeName
		}
		return out[i].Method < out[j].Method
	})
	return out
}

func (g *generator) collectDefinitionClosure(definitions map[string]*schemaNode) ([]string, error) {
	notifications, err := g.notificationSpecs()
	if err != nil {
		return nil, err
	}
	serverRequests, err := g.serverRequestSpecs()
	if err != nil {
		return nil, err
	}

	wanted := make(map[string]struct{}, len(coreDefinitions)+len(notifications)+len(serverRequests))
	for name := range coreDefinitions {
		wanted[name] = struct{}{}
	}
	for _, spec := range notifications {
		wanted[spec.TypeName] = struct{}{}
	}
	for _, spec := range serverRequests {
		wanted[spec.TypeName] = struct{}{}
	}

	queue := make([]string, 0, len(wanted))
	for name := range wanted {
		queue = append(queue, name)
	}

	seen := make(map[string]struct{}, len(queue))
	for len(queue) > 0 {
		last := len(queue) - 1
		name := queue[last]
		queue = queue[:last]

		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}

		definition := definitions[name]
		if definition == nil {
			continue
		}
		for refName := range referencedDefinitionNames(definition) {
			if _, ok := seen[refName]; !ok {
				queue = append(queue, refName)
			}
		}
	}

	out := make([]string, 0, len(seen))
	for name := range seen {
		out = append(out, name)
	}
	sort.Strings(out)
	return out, nil
}

func referencedDefinitionNames(schema *schemaNode) map[string]struct{} {
	refs := make(map[string]struct{})

	var visitNode func(*schemaNode)
	var visitValue func(*schemaValue)

	visitValue = func(value *schemaValue) {
		if value == nil || value.Node == nil {
			return
		}
		visitNode(value.Node)
	}

	visitNode = func(node *schemaNode) {
		if node == nil {
			return
		}

		if strings.HasPrefix(node.Ref, "#/definitions/") {
			refs[strings.TrimPrefix(node.Ref, "#/definitions/")] = struct{}{}
		}

		for _, branch := range node.OneOf {
			branch := branch
			visitValue(&branch)
		}
		for _, branch := range node.AnyOf {
			branch := branch
			visitValue(&branch)
		}
		for _, branch := range node.AllOf {
			branch := branch
			visitValue(&branch)
		}
		for _, property := range node.Properties {
			property := property
			visitValue(&property)
		}
		visitValue(node.AdditionalProperties)
		visitValue(node.Items)
	}

	visitNode(schema)
	return refs
}

func flattenStringEnumOneOf(definition *schemaNode) *schemaNode {
	if definition == nil || len(definition.OneOf) == 0 {
		return definition
	}

	enumValues := make([]schemaEnumValue, 0, len(definition.OneOf))
	for _, branch := range definition.OneOf {
		branchNode := branch.NodeOrNil()
		if branchNode == nil {
			return definition
		}
		enumValue, ok := branchNode.isStringEnumBranch()
		if !ok {
			return definition
		}
		enumValues = append(enumValues, schemaEnumValue{
			Kind:        schemaEnumValueString,
			StringValue: enumValue,
		})
	}

	out := cloneNode(definition)
	out.OneOf = nil
	out.Type = schemaType{Values: []string{"string"}}
	out.Enum = schemaEnum{Values: enumValues}
	return out
}

func flattenSingleAllOf(definition *schemaNode) *schemaNode {
	if definition == nil || len(definition.AllOf) != 1 {
		return definition
	}
	if definition.Ref != "" ||
		len(definition.OneOf) != 0 ||
		len(definition.AnyOf) != 0 ||
		len(definition.Properties) != 0 ||
		len(definition.Required) != 0 ||
		definition.AdditionalProperties != nil ||
		definition.Items != nil ||
		len(definition.Definitions) != 0 ||
		len(definition.Enum.Values) != 0 ||
		len(definition.Type.Values) != 0 ||
		definition.Format != "" {
		return definition
	}

	branchNode := definition.AllOf[0].NodeOrNil()
	if branchNode == nil {
		return definition
	}
	return cloneNode(branchNode)
}

func normalizeSchema(schema *schemaNode) (*schemaNode, bool) {
	current := flattenSingleAllOf(flattenStringEnumOneOf(cloneNode(schema)))
	nullable := false

	for {
		if current == nil || current.Ref != "" {
			return current, nullable
		}

		if nonNullType, ok := current.Type.NonNullSingleNullable(); ok {
			nullable = true
			next := cloneNode(current)
			next.Type = schemaType{Values: []string{nonNullType}}
			current = next
			continue
		}

		if branchNode, ok := singleNonNullBranch(current.AnyOf); ok {
			nullable = true
			current = flattenSingleAllOf(flattenStringEnumOneOf(cloneNode(branchNode)))
			continue
		}
		if branchNode, ok := singleNonNullBranch(current.OneOf); ok {
			nullable = true
			current = flattenSingleAllOf(flattenStringEnumOneOf(cloneNode(branchNode)))
			continue
		}

		return current, nullable
	}
}

func singleNonNullBranch(branches []schemaValue) (*schemaNode, bool) {
	if len(branches) == 0 {
		return nil, false
	}

	var candidate *schemaNode
	nullCount := 0
	nonNullCount := 0

	for _, branch := range branches {
		branchNode := branch.NodeOrNil()
		if branchNode == nil {
			nonNullCount++
			continue
		}
		if branchNode.Type.IsSingle("null") {
			nullCount++
			continue
		}
		nonNullCount++
		if candidate != nil {
			return nil, false
		}
		candidate = branchNode
	}

	if nonNullCount == 1 && nullCount > 0 && candidate != nil {
		return candidate, true
	}
	return nil, false
}

func isStringEnum(schema *schemaNode) bool {
	if schema == nil || !schema.Type.IsSingle("string") {
		return false
	}
	_, ok := schema.Enum.Strings()
	return ok
}

func toPascalCase(value string) string {
	parts := nonAlphaNumeric.Split(value, -1)
	normalized := make([]string, 0, len(parts))
	for _, part := range parts {
		if part == "" {
			continue
		}
		if initialism, ok := initialisms[strings.ToLower(part)]; ok {
			normalized = append(normalized, initialism)
			continue
		}

		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		normalized = append(normalized, string(runes))
	}

	compact := strings.Join(normalized, "")
	if compact == "" {
		return "Value"
	}
	if compact[0] >= '0' && compact[0] <= '9' {
		return "Value" + compact
	}
	return compact
}

func goFieldName(name string) string {
	fieldName := toPascalCase(name)
	if fieldName == "Jsonrpc" {
		return "JSONRPC"
	}
	return fieldName
}

func goTypeName(name string) string {
	return toPascalCase(name)
}

func goConstName(typeName, literal string) string {
	return typeName + toPascalCase(literal)
}

func scalarTypeForSchema(schema *schemaNode) (string, bool) {
	if schema == nil {
		return "", false
	}

	switch {
	case schema.Type.IsSingle("string"):
		return "string", true
	case schema.Type.IsSingle("boolean"):
		return "bool", true
	case schema.Type.IsSingle("integer"):
		switch {
		case schema.Format == "uint16":
			return "uint16", true
		case schema.Format == "uint32":
			return "uint32", true
		case schema.Format == "uint64":
			return "uint64", true
		case strings.HasPrefix(schema.Format, "uint"):
			return "uint64", true
		case schema.Format == "int32":
			return "int32", true
		case schema.Format == "int64":
			return "int64", true
		default:
			return "int64", true
		}
	case schema.Type.IsSingle("number"):
		return "float64", true
	default:
		return "", false
	}
}

func (r *goRenderer) fallbackExpr() ast.Expr {
	r.needsJSONImport = true
	return selectorExpr("json", "RawMessage")
}

func (r *goRenderer) fieldType(schema *schemaNode, required bool) ast.Expr {
	normalized, nullable := normalizeSchema(schema)
	expr := r.typeExpr(normalized)
	if isAnyExpr(expr) {
		return expr
	}
	if nullable || !required {
		if isRawMessageExpr(expr) {
			return expr
		}
		if isPointerLikeExpr(expr) || isAnyExpr(expr) {
			return expr
		}
		return &ast.StarExpr{X: expr}
	}
	return expr
}

func (r *goRenderer) topLevelDecl(name string, schema *schemaNode) []ast.Decl {
	normalized, _ := normalizeSchema(schema)
	typeName := goTypeName(name)

	if isStringEnum(normalized) {
		return r.stringEnumDecls(typeName, normalized)
	}

	if normalized != nil && normalized.Type.IsSingle("object") && len(normalized.Properties) != 0 {
		return []ast.Decl{r.structDecl(typeName, normalized)}
	}

	expr := r.typeExpr(normalized)
	spec := &ast.TypeSpec{
		Name: ident(typeName),
		Type: expr,
	}
	if isRawMessageExpr(expr) {
		spec.Assign = token.Pos(1)
	}
	return []ast.Decl{typeDecl(spec)}
}

func (r *goRenderer) stringEnumDecls(typeName string, schema *schemaNode) []ast.Decl {
	values, _ := schema.Enum.Strings()

	specs := make([]ast.Spec, 0, len(values))
	for _, value := range values {
		specs = append(specs, &ast.ValueSpec{
			Names:  []*ast.Ident{ident(goConstName(typeName, value))},
			Type:   ident(typeName),
			Values: []ast.Expr{stringLit(value)},
		})
	}

	return []ast.Decl{
		typeDecl(&ast.TypeSpec{
			Name: ident(typeName),
			Type: ident("string"),
		}),
		&ast.GenDecl{
			Tok:   token.CONST,
			Specs: specs,
		},
	}
}

func (r *goRenderer) structDecl(typeName string, schema *schemaNode) ast.Decl {
	if schema == nil || len(schema.Properties) == 0 {
		return typeDecl(&ast.TypeSpec{
			Name: ident(typeName),
			Type: mapTypeExpr(ident("string"), anyIdent()),
		})
	}

	requiredSet := make(map[string]struct{}, len(schema.Required))
	for _, name := range schema.Required {
		requiredSet[name] = struct{}{}
	}

	propNames := make([]string, 0, len(schema.Properties))
	for name := range schema.Properties {
		propNames = append(propNames, name)
	}
	sort.Strings(propNames)

	fields := make([]*ast.Field, 0, len(propNames))
	for _, wireName := range propNames {
		var fieldType ast.Expr = anyIdent()
		if propSchema, ok := schema.Properties[wireName]; ok && propSchema.Node != nil {
			_, required := requiredSet[wireName]
			fieldType = r.fieldType(propSchema.Node, required)
		}

		tag := wireName + ",omitempty"
		if _, required := requiredSet[wireName]; required {
			tag = wireName
		}

		fields = append(fields, &ast.Field{
			Names: []*ast.Ident{ident(goFieldName(wireName))},
			Type:  fieldType,
			Tag: &ast.BasicLit{
				Kind:  token.STRING,
				Value: fmt.Sprintf("`json:%q`", tag),
			},
		})
	}

	return typeDecl(&ast.TypeSpec{
		Name: ident(typeName),
		Type: &ast.StructType{
			Fields: &ast.FieldList{List: fields},
		},
	})
}

func (r *goRenderer) typeExprForValue(value *schemaValue) ast.Expr {
	if value == nil {
		return anyIdent()
	}
	if value.Node != nil {
		return r.typeExpr(value.Node)
	}
	if value.Bool != nil {
		if *value.Bool {
			return anyIdent()
		}
		return r.fallbackExpr()
	}
	return anyIdent()
}

func (r *goRenderer) typeExpr(schema *schemaNode) ast.Expr {
	if schema == nil {
		return anyIdent()
	}

	normalized, _ := normalizeSchema(schema)
	if normalized == nil {
		return anyIdent()
	}

	if strings.HasPrefix(normalized.Ref, "#/definitions/") {
		return ident(goTypeName(strings.TrimPrefix(normalized.Ref, "#/definitions/")))
	}
	if isStringEnum(normalized) {
		return ident("string")
	}
	if scalar, ok := scalarTypeForSchema(normalized); ok {
		return ident(scalar)
	}

	switch {
	case normalized.Type.IsSingle("array"):
		items := normalized.Items
		if items == nil {
			trueValue := true
			items = &schemaValue{Bool: &trueValue}
		}
		return &ast.ArrayType{
			Elt: r.typeExprForValue(items),
		}
	case normalized.Type.IsSingle("object"):
		if len(normalized.Properties) != 0 {
			return mapTypeExpr(ident("string"), anyIdent())
		}
		switch {
		case normalized.AdditionalProperties == nil:
			return mapTypeExpr(ident("string"), anyIdent())
		case normalized.AdditionalProperties.Node != nil:
			return mapTypeExpr(ident("string"), r.typeExpr(normalized.AdditionalProperties.Node))
		case normalized.AdditionalProperties.Bool != nil && *normalized.AdditionalProperties.Bool:
			return mapTypeExpr(ident("string"), anyIdent())
		default:
			return mapTypeExpr(ident("string"), anyIdent())
		}
	}

	if _, ok := normalized.Enum.Integers(); ok {
		return ident("int64")
	}
	if len(normalized.OneOf) != 0 || len(normalized.AnyOf) != 0 {
		return r.fallbackExpr()
	}
	return r.fallbackExpr()
}

func formatSourceBlocks(blocks []string) (string, error) {
	var buffer strings.Builder
	buffer.WriteString(generatorHeader)
	buffer.WriteString("package protocol\n\n")
	buffer.WriteString(strings.Join(blocks, "\n\n"))
	buffer.WriteByte('\n')
	return formatSource(buffer.String())
}

func formatSource(source string) (string, error) {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return "", err
	}
	return string(formatted), nil
}

func formatDecl(decl ast.Decl) (string, error) {
	var buffer bytes.Buffer
	if err := format.Node(&buffer, token.NewFileSet(), decl); err != nil {
		return "", err
	}
	return buffer.String(), nil
}

func formatExpr(expr ast.Expr) (string, error) {
	var buffer bytes.Buffer
	if err := format.Node(&buffer, token.NewFileSet(), expr); err != nil {
		return "", err
	}
	return buffer.String(), nil
}

func renderMethodFactoryMapSource(name, valueType string, specs []methodSpec) (string, error) {
	mapType, err := formatExpr(mapTypeExpr(ident("string"), ident(valueType)))
	if err != nil {
		return "", err
	}

	lines := make([]string, 0, len(specs)+2)
	lines = append(lines, fmt.Sprintf("var %s = %s{", name, mapType))
	for _, spec := range specs {
		funcLiteral, err := formatExpr(factoryFuncLiteral(spec.TypeName))
		if err != nil {
			return "", err
		}
		lines = append(lines, indentBlock(fmt.Sprintf("%q: %s,", spec.Method, funcLiteral), "\t"))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n"), nil
}

func indentBlock(block, prefix string) string {
	lines := strings.Split(block, "\n")
	for i, line := range lines {
		lines[i] = prefix + line
	}
	return strings.Join(lines, "\n")
}

func ident(name string) *ast.Ident {
	return ast.NewIdent(name)
}

func anyIdent() *ast.Ident {
	return ident("any")
}

func stringLit(value string) *ast.BasicLit {
	return &ast.BasicLit{
		Kind:  token.STRING,
		Value: strconv.Quote(value),
	}
}

func selectorExpr(pkg, name string) *ast.SelectorExpr {
	return &ast.SelectorExpr{
		X:   ident(pkg),
		Sel: ident(name),
	}
}

func mapTypeExpr(key, value ast.Expr) *ast.MapType {
	return &ast.MapType{
		Key:   key,
		Value: value,
	}
}

func funcTypeNoArgs(result ast.Expr) *ast.FuncType {
	return &ast.FuncType{
		Params: &ast.FieldList{},
		Results: &ast.FieldList{
			List: []*ast.Field{{Type: result}},
		},
	}
}

func importDecl(path string) ast.Decl {
	return &ast.GenDecl{
		Tok: token.IMPORT,
		Specs: []ast.Spec{
			&ast.ImportSpec{
				Path: stringLit(path),
			},
		},
	}
}

func typeDecl(spec *ast.TypeSpec) ast.Decl {
	return &ast.GenDecl{
		Tok: token.TYPE,
		Specs: []ast.Spec{
			spec,
		},
	}
}

func typeAliasDecl(name string, typ ast.Expr) ast.Decl {
	return &ast.GenDecl{
		Tok: token.TYPE,
		Specs: []ast.Spec{
			&ast.TypeSpec{
				Name:   ident(name),
				Assign: token.Pos(1),
				Type:   typ,
			},
		},
	}
}

func factoryFuncLiteral(typeName string) *ast.FuncLit {
	return &ast.FuncLit{
		Type: funcTypeNoArgs(anyIdent()),
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.ReturnStmt{
					Results: []ast.Expr{
						&ast.UnaryExpr{
							Op: token.AND,
							X: &ast.CompositeLit{
								Type: ident(goTypeName(typeName)),
							},
						},
					},
				},
			},
		},
	}
}

func isAnyExpr(expr ast.Expr) bool {
	identifier, ok := expr.(*ast.Ident)
	return ok && identifier.Name == "any"
}

func isRawMessageExpr(expr ast.Expr) bool {
	selector, ok := expr.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	pkg, ok := selector.X.(*ast.Ident)
	return ok && pkg.Name == "json" && selector.Sel.Name == "RawMessage"
}

func isPointerLikeExpr(expr ast.Expr) bool {
	switch expr.(type) {
	case *ast.StarExpr, *ast.ArrayType, *ast.MapType:
		return true
	default:
		return false
	}
}
